### ISSUE TITLE
ruby-saml 1.4.3 requires Recipient validation so settings.assertion_consumer_service_url must be provided

### ISSUE THREAD

**Issue by pitbulk** [apokalipto/devise_saml_authenticatable#100]
Review https://github.com/onelogin/ruby-saml/issues/399

**Comment by adamstegman** [comment]
Thank you for the notice! We may want to at the very least update documentation, or consider validating settings (though I'd prefer if ruby-saml itself could do that).

**Comment by pitbulk** [comment]
If the skip_destination is  used then SP ACS url is required, that why I can't validate settings throwing errors if no SP ACS URL.

But if your use of ruby-saml doesn't use skip_destination (I recommend to never skip security checks), then SP ACS URL need to be provided and match SAMLResponse SubjectConfirmation Recipient.
