### ISSUE TITLE
OneLogin: "You do not have access to this application."

### ISSUE THREAD

**Issue by nickcoyne** [apokalipto/devise_saml_authenticatable#103]
I've followed the setup instructions at https://github.com/apokalipto/devise_saml_authenticatable/wiki/OneLogin, and have my app setup.

When I click through the "sign_in" link, I get a redirect and then a "You do not have access to this application." message from OneLogin. No login form is presented and I'm at a loss as to what settings I'm missing here, or even what to check next.

**Comment by adamstegman** [comment]
Sorry for the late reply!

You may be missing permission to access the application in OneLogin. Are you listed in the Users of the app?

**Comment by nickcoyne** [comment]
@adamstegman spot on there. I was logged in as an admin for doing all the onelogin config, and of course that user had no app access. Using a different browser for the app login was the solution. Thanks!
