### ISSUE TITLE
SAML logout from an api controller

### ISSUE THREAD

**Issue by nickcoyne** [apokalipto/devise_saml_authenticatable#104]
I've got SAML auth successfully integrated except for one thing...

For logout from my web app I use `destroy_user_session_path` and that does all the necessary to successfully log the user out and redirect them to the login page.

However I also have an api logout method that is not working with SAML. I have a `current_user` controller with a `destroy` method:
```ruby
def destroy
  sign_out(current_user)
  head :no_content
end
```

However it does not log the user out, and I'm not clear how I'll achieve that from within this controller?

**Comment by nickcoyne** [comment]
On further thought, I think I'd probably need to use the OneLogin API to perform the logout?

**Comment by nickcoyne** [comment]
I've sorted this via the API.

**Comment by davidcharlesweber** [comment]
@nickcoyne How were you able to configure the logout? The documentation is rather vague here. I have the session_index being set but many errors during the logout from the provider (in one case onelogin)

**Comment by nickcoyne** [comment]
@davidcharlesweber I created a service to perform the logout (and a few other things too) like this (just showing the logout parts).

```ruby
class OneloginService
  include HTTParty
  base_uri 'https://youraccount.onelogin.com'

  attr_reader :user

  def initialize(user: nil)
    @user = user
  end

  def logout
    return if user.blank?

    client.log_user_out(onelogin_user.id) if onelogin_user
  end

  private

  def onelogin_user
    @onelogin_user ||= client.get_users(email: user.email).first
  end

  def client
    @client ||=
      OneLogin::Api::Client.new(
        client_id: ENV['ONELOGIN_CLIENT_ID'],
        client_secret: ENV['ONELOGIN_CLIENT_SECRET'],
        region: 'us'
      )
  end
end
```

and then in my api `current_user_controller.rb` I simply have

```ruby
def destroy
  OneloginService.new(user: current_user).logout
  sign_out(current_user)

  head :no_content
end
```
