### ISSUE TITLE
Redirect back to root_path

### ISSUE THREAD

**Issue by chabgood** [apokalipto/devise_saml_authenticatable#105]
I am getting redirect back to root_path:

Started GET "/users/saml/sign_in" for ::1 at 2017-12-28 15:00:56 -0600
Processing by Devise::SamlSessionsController#new as HTML
Remote_Addr: ::1 Load Balancer:  Client IP:
Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='http://localhost:3000/users/saml/auth' Destination='' ID='_9087011d-74c6-434a-80cd-9050c05350c3' IssueInstant='2017-12-28T21:00:57Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://localhost:3000/saml/metadata</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:2.0:nameid-format:transient'/><samlp:RequestedAuthnContext Comparison='exact'><saml:AuthnContextClassRef></saml:AuthnContextClassRef></samlp:RequestedAuthnContext></samlp:AuthnRequest>
Redirected to http://localhost:3000?SAMLRequest=fVJNT8MwDP0rveVUmrYb26K2UtUJadJAaAMOXJCVelqlNCmJC%2BPfk5YN9QC75GC%2FD%2Fs5mYNWdaLs6ah3%2BN6jo6B0Di01RldGu75Fu0f70Uh83m1zdiTqRBQpI0EdjSORcs6j3jNcNGhF4KVYsPZCjYZBJWcs2Kxz9rbiywWP4zpczORtOEtnEC65rMMVn3PJ56l%2FUw91rseNdgSacpbweBHGSZgsn5JYcC7mi1cWvHi3UTm54Sw4tUo7MZjnrLdaGHCNExpadIKk2Jf3W%2BGBAi57TSnddU5nDRlpFCuyAS3G6Wzxdwrj%2Fi0S1ECQRVNC9pPzgzfYrB%2BNauRXUCplPiuLQJgzsj2y4M7YFuj6SEOlqcPDCBVkQbsGNbHoYnK%2BI9bjVf0RCU8UVKbtwDZuiA1PIOmy0hRVKR%2FSDg%2FFeforvX98frvTL1V8Aw%3D%3D
Completed 302 Found in 4ms (ActiveRecord: 0.5ms)

Started GET "/?SAMLRequest=fVJNT8MwDP0rveVUmrYb26K2UtUJadJAaAMOXJCVelqlNCmJC%2BPfk5YN9QC75GC%2FD%2Fs5mYNWdaLs6ah3%2BN6jo6B0Di01RldGu75Fu0f70Uh83m1zdiTqRBQpI0EdjSORcs6j3jNcNGhF4KVYsPZCjYZBJWcs2Kxz9rbiywWP4zpczORtOEtnEC65rMMVn3PJ56l%2FUw91rseNdgSacpbweBHGSZgsn5JYcC7mi1cWvHi3UTm54Sw4tUo7MZjnrLdaGHCNExpadIKk2Jf3W%2BGBAi57TSnddU5nDRlpFCuyAS3G6Wzxdwrj%2Fi0S1ECQRVNC9pPzgzfYrB%2BNauRXUCplPiuLQJgzsj2y4M7YFuj6SEOlqcPDCBVkQbsGNbHoYnK%2BI9bjVf0RCU8UVKbtwDZuiA1PIOmy0hRVKR%2FSDg%2FFeforvX98frvTL1V8Aw%3D%3D" for ::1 at 2017-12-28 15:00:57 -0600
Processing by PagesController#home as HTML
  Parameters: {"SAMLRequest"=>"fVJNT8MwDP0rveVUmrYb26K2UtUJadJAaAMOXJCVelqlNCmJC+Pfk5YN9QC75GC/D/s5mYNWdaLs6ah3+N6jo6B0Di01RldGu75Fu0f70Uh83m1zdiTqRBQpI0EdjSORcs6j3jNcNGhF4KVYsPZCjYZBJWcs2Kxz9rbiywWP4zpczORtOEtnEC65rMMVn3PJ56l/Uw91rseNdgSacpbweBHGSZgsn5JYcC7mi1cWvHi3UTm54Sw4tUo7MZjnrLdaGHCNExpadIKk2Jf3W+GBAi57TSnddU5nDRlpFCuyAS3G6Wzxdwrj/i0S1ECQRVNC9pPzgzfYrB+NauRXUCplPiuLQJgzsj2y4M7YFuj6SEOlqcPDCBVkQbsGNbHoYnK+I9bjVf0RCU8UVKbtwDZuiA1PIOmy0hRVKR/SDg/FeforvX98frvTL1V8Aw=="}
Remote_Addr: ::1 Load Balancer:  Client IP:

I have no idea why.

**Comment by adamstegman** [comment]
It looks like your IdP Target URLs are configured to localhost. You should be able to find those URLs in your IdP configuration. We have some wiki pages for OneLogin and Okta written up if you’re using one of those. 

If you’d like, you could copy your SAML config into this issue (maybe redact sensitive IDs), and I'll take a look.
