### ISSUE TITLE
incomplete multiple IDP support

### ISSUE THREAD

**Issue by bmesuere** [apokalipto/devise_saml_authenticatable#108]
I'm trying to use this gem with multiple IDPs as described in the readme, but I'm struggling a bit.

By default, the response of `idp_entity_id_reader` is used to select which idp should be used, based on the SAML request or response. However, when a user selects his educational institution (idp) in my application, the request isn't created yet and the settings are needed to create it which is a chicken-and-egg situation. I created a custom `idp_entity_id_reader` which also checks the `institution` param. This way I can select which config (and single sign on url) to use by creating urls of the form `/users/saml/sign_in/?institution=xxx` on my institution selection screen. This works as expected.

As a next step, I now want to store the idp that was used to sign in to be able to redirect users to the correct single log out page. I had 2 approaches in mind: store it in the database as a property of my user or store it in the session.
The first approach failed because there doesn't seem to be a way to get that information in my user model. The only way to get information in the model is by using the attribute mapping, but the idp isn't an attribute.
The second approach failed because in my custom `idp_entity_id_reader`, the session context isn't available.

What would be the best approach to handle this? I think everyone using multiple idps must have encountered a similar problem.

**Comment by bmesuere** [comment]
In the current version of the gem, SP initiated sign out is not working with multiple IDPs. The action that is called on sign out doesn't use the entity_id detection:

```
  def after_sign_out_path_for(_)
    request = OneLogin::RubySaml::Logoutrequest.new
    request.create(saml_config)
  end
```

This should at least be adapted to something like:
```
  def after_sign_out_path_for(_)
    idp_entity_id = get_idp_entity_id(params)
    request = OneLogin::RubySaml::Logoutrequest.new
    request.create(saml_config(idp_entity_id))
  end
```

**Comment by adamstegman** [comment]
Thanks for bringing this issue up! I don't have an environment with multiple IdPs, so this is difficult for me to test—I'm relying on people like you pointing out these issues and trying out fixes. Have you tried that change in a local version of the gem?

Maybe we could add an integration test against multiple IdPs that might catch this sort of issue?

**Comment by bmesuere** [comment]
I have monkey patched the `after_sign_out_path_for` method with the code posted above and this works for me.

Do note that the default `get_idp_entity_id` probably also will not suffice for most people. I extended that function with a check for a custom url parameter to select an entity id.

**Comment by adamstegman** [comment]
Yeah, I think given the current API, most heuristics to choose which IdP config to use will have to be custom. 

There's probably a more robust, opinionated way to configure multiple IdPs that would clean things up for a potential v2.

**Comment by bmesuere** [comment]
Sounds good! Support for idp-specific attribute maps might also come in handy (although I saw there's an open pull request that would mostly solve this).
