### ISSUE TITLE
Override user creation

### ISSUE THREAD

**Issue by chabgood** [apokalipto/devise_saml_authenticatable#114]
I have been browsing around a bit in the code  but I cannot seem to figure out how to override the user creation.  We have users in our Db and I need to find one first.  Do you have ideas?

**Comment by adamstegman** [comment]
There's a few relevant things:

- Ideally your users would be located using the subject or email from the SAML response. Then you don't need to override anything. Set `config.saml_use_subject` to `true` to use the SAML subject and `config.saml_default_user_key` to set the column name to search by.
- Set `config.saml_create_user` and `config.saml_update_user` to `true` so users are created and updated from SAML responses.
- If you're locating your users some other way (how?) then you can set `config.saml_resource_locator` to a `Proc` that's called with: the model class, the SAML response, and the "auth value," which should be a unique user key (subject or email, depending on your config). See https://github.com/apokalipto/devise_saml_authenticatable/blob/4ff6d40fec3611f83f94c4cedfd41a64be741b1d/lib/devise_saml_authenticatable/model.rb#L45.
- If you want control over users that are created/updated, then you can set `config.saml_update_resource_hook` to a `Proc` that's called with: the user object, the SAML response, and the "auth value" (see above). See https://github.com/apokalipto/devise_saml_authenticatable/blob/4ff6d40fec3611f83f94c4cedfd41a64be741b1d/lib/devise_saml_authenticatable/model.rb#L65.

**Comment by chabgood** [comment]
Sorry, but I am not quite sure what you are trying to say above,
