### ISSUE TITLE
Support for multiple attribute mappings

### ISSUE THREAD

**Issue by tkalliom** [apokalipto/devise_saml_authenticatable#119]
In the case where you are supporting IdPs which have different schemas known to have no overlap, it would be nice if the attribute mapping worked such that you could do something like this:

```yaml
# OID schema
"urn:oid:0.9.2342.19200300.100.1.3": "email"
"urn:oid:2.5.4.3": "name"

# Identity Metasystem Interoperability schema
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "email"
"http://schemas.xmlsoap.org/claims/CommonName": "name"
```

`SamlMappedAttributes#value_by_resource_key` could check the response for any attributes mapped to the given `key` and perhaps raise an exception if there is more than one match.

**Comment by aneziocampos** [comment]
+1
