### ISSUE TITLE
attribute-map.yml

### ISSUE THREAD

**Issue by CR1AT0RS** [apokalipto/devise_saml_authenticatable#121]
# attribute-map.yml

  "urn:mace:dir:attribute-def:uid": "uid"
  "urn:mace:dir:attribute-def:email": "email"
  "urn:mace:dir:attribute-def:name": "last_name"
  "urn:mace:dir:attribute-def:lastName": "name"

**I have corresponding entries in database too. But only email gets stored in the database. Any ideas how can I parse these items from my XML ? 

I can see in SAML response from my google app. The values for email, name and last_name are being provided by the google app response. Do I need to modify the file here:** 
`devise_saml_authenticatable/spec/devise_saml_authenticatable/model_spec.rb

require 'spec_helper'

describe Devise::Models::SamlAuthenticatable do
  class Model
    include Devise::Models::SamlAuthenticatable
    attr_accessor :email, :name, :saved
    def initialize(params = {})
      @email = params[:email]
      @name = params[:name]
      @new_record = params.fetch(:new_record, true)
    end
`

**Comment by adamstegman** [comment]
Are you sure the SAML attributes are correct? I haven't seen good documentation on this for a specific IdP, I've just had to look at the XML returned by the IdP to see what the attribute map should look like.

If you've set `saml_create_user` and `saml_update_user` to `true`, this gem will automatically use the values from the response to set the model attributes in your database. It uses your attribute map to find them in the XML: https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable.rb#L85

**Comment by CR1AT0RS** [comment]
My IdP is google actually. My SAML response looks like this:

>   <saml2:AttributeStatement>
>       <saml2:Attribute Name="email">
>         <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">justin@gmail.com</saml2:AttributeValue>
>       </saml2:Attribute>
>       <saml2:Attribute Name="name">
>         <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">Justin</saml2:AttributeValue>
>       </saml2:Attribute>
>       <saml2:Attribute Name="lastname">
>         <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">Smith</saml2:AttributeValue>
>       </saml2:Attribute>
>       <saml2:Attribute Name="uid"/>
>     </saml2:AttributeStatement>

**Comment by adamstegman** [comment]
OK, I think you want to use the `Name` as the key in the attribute-map:

```yaml
email: email
name: name
lastname: last_name
```

**Comment by CR1AT0RS** [comment]
Here's my attribute mapping(latest):
<img width="1079" alt="screen shot 2018-06-29 at 4 18 02 pm" src="https://user-images.githubusercontent.com/4299288/42118510-663e74dc-7bb8-11e8-9107-a24ba04050be.png">

Also here's my attribute-map.xml
  "urn:mace:dir:attribute-def:email": "email"
  "urn:mace:dir:attribute-def:name": "last_name"
  "urn:mace:dir:attribute-def:giveName": "name"

Here's the fields in DB:
<img width="442" alt="screen shot 2018-06-29 at 4 22 00 pm" src="https://user-images.githubusercontent.com/4299288/42118529-952014a4-7bb8-11e8-957d-f4f1538dd8b8.png">

But the email field is the only one that get's filled up. Name/LastName fields are always nil. I have tried everything now but can't make it work. Is there a way to test what's wrong/missing ?

**Comment by adamstegman** [comment]
There's not a built-in way—what I usually do to look into it is run `bundle open devise_saml_authenticatable`, and add some debug logging to see what the responses look like, versus my attribute map. [The update hook I linked above](https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable.rb#L85) would be a good place to start, since you have access to the [response](https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable/saml_response.rb) as well as [the attribute map inside the decorated response](https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable/saml_mapped_attributes.rb).

**Comment by mattbaumann1** [comment]
I am continuing to have an issue with the attribute-map.yml file. It doesn't pull in any of the variables mapped in the file. I have tried this a couple of different ways. Below I have included the SAML response and two of the versions of the attribute-map.yml file that I have tried. I am having the same problem as @CR1AT0RS . The only attribute that is pulled in on user creation is the email. 

`
# SAML RESPONSE TRANSLATED
# Attributes
array (
  'lastName' => 
  array (
    0 => 'LName7',
  ),
  'firstName' => 
  array (
    0 => 'FName7',
  ),
  'email' => 
  array (
    0 => 'test7@test.com',
  ),
)

# NameID
array (
  'Value' => 'test7@test.com',
  'Format' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
)


# attribute-map.yml
"email": "email"
"firstName": "first_name"
"lastName": "last_name"

# Console of user created. 
User Load (0.5ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => #<User id: 27, organization_id: nil, organization_role: "none", email: "test7@test.com", first_name: nil, last_name: nil, era_commons: nil, created_at: "2019-07-15 03:40:58", updated_at: "2019-07-15 03:40:58"> 
2.6.1 :033 > 

# attribute-map.yml try #2
"urn:mace:dir:attribute-def:email": "email"
"urn:mace:dir:attribute-def:firstName": "first_name"
"urn:mace:dir:attribute-def:lastName": "last_name"

# Console of user created with try #2. 
User Load (0.6ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => #<User id: 28, organization_id: nil, organization_role: "none", email: "test7@test.com", first_name: nil, last_name: nil, era_commons: nil, created_at: "2019-07-15 03:46:22", updated_at: "2019-07-15 03:46:22"> 
2.6.1 :049 > 


# devise.rb settings
# ==> Configuration for :saml_authenticatable

  # Create user if the user does not exist. (Default is false)
  config.saml_create_user = true

  # Update the attributes of the user after a successful login. (Default is false)
  config.saml_update_user = true

  # Set the default user key. The user will be looked up by this key. Make
  # sure that the Authentication Response includes the attribute.
  config.saml_default_user_key = :email

  # Optional. This stores the session index defined by the IDP during login.  If provided it will be used as a salt
  # for the user's session to facilitate an IDP initiated logout request.
  config.saml_session_index_key = :session_index

  # You can set this value to use Subject or SAML assertation as info to which email will be compared.
  # If you don't set it then email will be extracted from SAML assertation attributes.
  config.saml_use_subject = true

  # You can support multiple IdPs by setting this value to a class that implements a #settings method which takes
  # an IdP entity id as an argument and returns a hash of idp settings for the corresponding IdP.
  config.idp_settings_adapter = nil

  # You provide you own method to find the idp_entity_id in a SAML message in the case of multiple IdPs
  # by setting this to a custom reader class, or use the default.
  # config.idp_entity_id_reader = DeviseSamlAuthenticatable::DefaultIdpEntityIdReader

  # You can set a handler object that takes the response for a failed SAML request and the strategy,
  # and implements a #handle method. This method can then redirect the user, return error messages, etc.
  # config.saml_failed_callback = nil

  # You can customize the named routes generated in case of named route collisions with
  # other Devise modules or libraries. Set the saml_route_helper_prefix to a string that will
  # be appended to the named route.
  # If saml_route_helper_prefix = 'saml' then the new_user_session route becomes new_saml_user_session
  # config.saml_route_helper_prefix = 'saml'
`

**Comment by mattbaumann1** [comment]
`# ==> Configuration for :saml_authenticatable

  # Create user if the user does not exist. (Default is false)
  config.saml_create_user = true

  # Update the attributes of the user after a successful login. (Default is false)
  config.saml_update_user = true

  # Set the default user key. The user will be looked up by this key. Make
  # sure that the Authentication Response includes the attribute.
  config.saml_default_user_key = :email

  # Optional. This stores the session index defined by the IDP during login.  If provided it will be used as a salt
  # for the user's session to facilitate an IDP initiated logout request.
  config.saml_session_index_key = :session_index

  # You can set this value to use Subject or SAML assertation as info to which email will be compared.
  # If you don't set it then email will be extracted from SAML assertation attributes.
  config.saml_use_subject = true

  # You can support multiple IdPs by setting this value to a class that implements a #settings method which takes
  # an IdP entity id as an argument and returns a hash of idp settings for the corresponding IdP.
  config.idp_settings_adapter = nil

  # You provide you own method to find the idp_entity_id in a SAML message in the case of multiple IdPs
  # by setting this to a custom reader class, or use the default.
  # config.idp_entity_id_reader = DeviseSamlAuthenticatable::DefaultIdpEntityIdReader

  # You can set a handler object that takes the response for a failed SAML request and the strategy,
  # and implements a #handle method. This method can then redirect the user, return error messages, etc.
  # config.saml_failed_callback = nil

  # You can customize the named routes generated in case of named route collisions with
  # other Devise modules or libraries. Set the saml_route_helper_prefix to a string that will
  # be appended to the named route.
  # If saml_route_helper_prefix = 'saml' then the new_user_session route becomes new_saml_user_session
  # config.saml_route_helper_prefix = 'saml'`

**Comment by adamstegman** [comment]
Interesting, it looks like your first attribute map should have worked.

Can you try the debugging process I outlined above? Run `bundle open devise_saml_authenticatable`, and add some debug logging to see what the response and attribute map look like. I'm especially interested in [this method](https://github.com/apokalipto/devise_saml_authenticatable/blob/3934b53af92a4ea91b3d3c266535c020a4b807c9/lib/devise_saml_authenticatable/saml_mapped_attributes.rb#L16), and what the value of `attribute_map_for_key` is, and the value of `saml_key` and `saml_value` in each iteration of the loop.

**Comment by mattbaumann1** [comment]
> Interesting, it looks like your first attribute map should have worked.
> 
> Can you try the debugging process I outlined above? Run `bundle open devise_saml_authenticatable`, and add some debug logging to see what the response and attribute map look like. I'm especially interested in [this method](https://github.com/apokalipto/devise_saml_authenticatable/blob/3934b53af92a4ea91b3d3c266535c020a4b807c9/lib/devise_saml_authenticatable/saml_mapped_attributes.rb#L16), and what the value of `attribute_map_for_key` is, and the value of `saml_key` and `saml_value` in each iteration of the loop.


Thank you for the reply. I deleted my comment because it was an issue on my end that was causing the problem. I had separated out the code and thrown it in the credentials file and it seems that the loading of the attribute-map.yml file couldn't handle that.
