### ISSUE TITLE
custom saml_sessions controller/override user_session path

### ISSUE THREAD

**Issue by trentbullard** [apokalipto/devise_saml_authenticatable#123]
Not sure if this is the right place, but

This is my routes.rb
```
devise_for :users, controllers: {sessions: "saml_sessions"}, skip: [:registrations, :passwords]
```

when i do rake routes it still says 
```
user_session POST     /users/saml/auth(.:format)     devise/saml_sessions#create
```

I also add 
```
devise_scope :user do
    post "users/saml/auth" => "saml_sessions#create", as: :user_session
end
```
but this creates an error due to multipe routes named `user_session`

if i remove `as: :user_session`, it simply creates 2 routes for `/users/saml/auth` with different names, and always defaults to the `devise/saml_sessions#create` action when i access the route.

What do I need to change in order to have `/users/saml/auth` route to my custom saml_sessions_controller.rb?

**Comment by adamstegman** [comment]
Try updating the original route to be `devise_for :users, skip: [:sessions]`. Then you can add your custom route.
