### ISSUE TITLE
How to use this gem if my IDP won't return user password to my SP when a user is successfully authenticated?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [apokalipto/devise_saml_authenticatable#125]
I got this error:

```
ActiveRecord::RecordInvalid in Devise::SamlSessionsController#create
Validation failed: Password can't be blank
```

I guess it's because when I login to devise, devise wants to create a new user, and devise have presence validation on password, it doesn't see me giving it any password, so it complains. (I could be wrong)

When I login to IDP successfully, my IDP return these to my service provider:

- 2 attributes (my name and my email address)
- 1 name ID (my ID)

My IDP doesn't return password to SP and my IDP team said we are not meant to pass password around when using SAML.

My service provider is configured with the following setting:

```
  config.saml_create_user = true
  config.saml_update_user = true
  config.saml_default_user_key = :email
  config.saml_session_index_key = :session_index
  config.saml_use_subject = false
  config.idp_settings_adapter = nil
```

Is there any way for me to safely and securely use devise without passing password to the application? This should be a sensible way of doing things right? Because if we are going to use SAML to ask IDP to authenticate user every time, we don't really need to keep track of use's password right? We can just ask IDP to do that for us.

Also, reading the README file and code, I don't really understand `saml_default_user_key`, can anyone please explain why we have to include this key and what is it used for?

Also it seems like `saml_default_user_key` is heavily related to `saml_use_subject`, which I don't understand too, especially about why do we need to compare it to email?

**Comment by adamstegman** [comment]
If you’re using SSO, your application should not need any passwords stored. The IdP handles all of that for you. So if you only use SSO, you can remove the password column from your table entirely. If you’re still allowing people to log in with both database and SAML authentication, there’s a bit more to it, I’d start here: https://github.com/apokalipto/devise_saml_authenticatable/wiki/Supporting-multiple-authentication-strategies. You’ll have to disable the validation you’re running into for only those users.

`saml_default_user_key` is the column on your users table that identifies your user. It may be an `email` (which is the default), or a `username`, or something like that. If you have `saml_use_subject` turned on, this gem will use the Subject of your IdP’s response to identify the user; if it is off the gem will find the key in the attribute map config file, and look up the value in the SAML response’s attributes.
