### ISSUE TITLE
Is it possible to do SP initiated log out?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [apokalipto/devise_saml_authenticatable#128]
Hi, in my application, I need SP initiated log out.

And when creating the `OneLogin::RubySaml::Logoutrequest.new` object in `after_sign_out_path_for(_)`, I had to monkey patch the method so that the `saml_config(idp_entity_id)` object contain these two attributes:
1) saml_settings.name_identifier_value = "My organisation's special identifier here - e.g. User.first.id"
2) saml_settings.sessionindex = "the session index here - e.g. User.first.session_index"

My temporary code is below:
```
# This is my temporary hack/monkey-patch
  def after_sign_out_path_for(_)
    idp_entity_id = get_idp_entity_id(params)
    request = OneLogin::RubySaml::Logoutrequest.new

# My code
saml_settings = saml_config(idp_entity_id)
saml_settings.name_identifier_value = "My organisation's special identifier here"
saml_settings.sessionindex = "the session index here"
request.create(saml_settings)
# my code ends

# The code it replaces
    # request.create(saml_config(idp_entity_id))
#The code it replaces ends
  end
```

Both of the attributes I said I need above are attributes of the user model.

I find it challenging to access the two attributes I need from the user object, because current_user already signed out in the destroy method of devise sessions_controller.rb, and I need it in the `after_sign_out_path_for` method, which happen after the `destroy` method, and I can't think of other good way to access the 2 attributes I want above without using `current_user`.

Is there a way to do SP initiated single logout using this gem? If not, what is the best way to monkey patch it (or pull request?)? Does anyone have any suggestion?

**Comment by adamstegman** [comment]
I think your instinct to override that method is correct. Maybe you could store those values in an instance variable in the controller in a `before_action`, and then read those variables in that `after_sign_out_path_for` method.

**Comment by Yu-Chieh-Henry-Yang** [comment]
Yes, this is my new hack which is more generic (all inside `Devise::SamlSessionsController`):

```
  if Rails::VERSION::MAJOR < 5
    skip_before_filter :verify_authenticity_token
    prepend_before_filter :store_info_for_sp_initiated_logout, only: :destroy #my code
  else
    skip_before_action :verify_authenticity_token, raise: false
    prepend_before_action :store_info_for_sp_initiated_logout, only: :destroy #my code
  end

#my code begins
  def store_info_for_sp_initiated_logout
    @name_identifier_value_for_sp_initiated_logout = current_user.id
    @sessionindex_for_sp_initiated_logout = current_user.session_index
  end
#my code ends


  # Override devise to send user to IdP logout for SLO
  def after_sign_out_path_for(_)
    idp_entity_id = get_idp_entity_id(params)
    request = OneLogin::RubySaml::Logoutrequest.new

#my code begins
saml_settings = saml_config(idp_entity_id)
saml_settings.name_identifier_value = @name_identifier_value_for_sp_initiated_logout
saml_settings.sessionindex = @sessionindex_for_sp_initiated_logout
@name_identifier_value_for_sp_initiated_logout = nil
@sessionindex_for_sp_initiated_logout = nil
request.create(saml_settings)
#my code ends

    # request.create(saml_config(idp_entity_id)) #I commented this out
  end
```

@adamstegman Do you think we can do a pull request to integrate SP initiated logout feature into the code base? (i'm happy to do a pull request if it doesn't shake the code base too much)
If yes, how do you think we should go about that?

**Comment by adamstegman** [comment]
@Yu-Chieh-Henry-Yang I'm not sure what kind of generic modification would suit your needs. It seems like your IdP requires some specific settings. It might be nice to make the `request` or `params` available to the `idp_settings_adapter`, but that might require some refactoring.

**Comment by Yu-Chieh-Henry-Yang** [comment]
I think https://github.com/apokalipto/devise_saml_authenticatable/issues/147 answers the question so closing this issue.
