### ISSUE TITLE
Support for using Ping Identity as IDP

### ISSUE THREAD

**Issue by liujohnson118** [apokalipto/devise_saml_authenticatable#141]
I've tested my rails project using this gem and SSO with Okta and Onelogin as IDPs. They work fabulously and thanks for the awesome gem!

Now, I'm trying to integrate SSO using Ping Identity as IDP. So far I haven't found any guide or wiki or videos explaining how to do it. 

In my devise.rb file I have
  ```
config.saml_route_helper_prefix = 'saml'
  # ==> SAML
  config.saml_create_user = true
  config.saml_update_user = true
  config.saml_default_user_key = :email
  config.saml_session_index_key = :session_index
  config.saml_use_subject = true
  config.idp_entity_id_reader = DeviseSamlAuthenticatable::DefaultIdpEntityIdReader
  config.idp_settings_adapter = nil

  config.saml_configure do |settings|
    settings.assertion_consumer_service_url     = "#{Settings.devise_callback}/users/saml/auth"
    settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    settings.name_identifier_format             = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
    settings.issuer                             = Settings.xxx.sso.idp_entity_id #something like "https://auth2test.xxx.ca"
    settings.idp_entity_id                      = Settings.xxx.sso.idp_entity_id #something like "https://auth2test.xxx.ca"
    settings.authn_context                      = ""
    settings.idp_slo_target_url                 = "https://auth2test.xxx.ca/idp/SSO.saml2"
    settings.idp_sso_target_url                 = "https://auth2test.xxx.ca/idp/SLO.saml2"
    settings.idp_cert_fingerprint               = "B0:39...."
    settings.idp_cert_fingerprint_algorithm     = 'http://www.w3.org/2000/09/xmldsig#sha256'
  end

```
But when being redirected to IDP's login page, I got 

```
Unexpected System Error
Sorry for the inconvenience. Please contact your administrator for assistance and provide the reference number below to help locate and correct the problem.
Reference#: xxxx
```
Also, I see that for `settings.issuer` in devise.rb, the wikis for Onelogin and Okta require "somehost:port/users/saml/metadata". But on https://github.com/apokalipto/devise_saml_authenticatable, it says 

"Your IdP should give you some information you need to configure in ruby-saml, as in the next section:

Issuer (idp_entity_id)
"
Is the issuer the same as idp_entity_id? I've tried using "somehost:port/users/saml/metadata" for `settings.issuer` with Ping Identity as IDP, and got error `Issuer of the Assertion not found or multiple.`

```
          unless issuer_assertion_nodes.size == 1
            error_msg = "Issuer of the Assertion not found or multiple."
            raise ValidationError.new(error_msg)
          end

          nodes = issuer_response_nodes + issuer_assertion_nodes
```
Location of this code is in `vendor/bundle/ruby/2.4.0/gems/ruby-saml-1.9.0/lib/onelogin/ruby-saml/response.rb:295:in `issuers'`. But that worked for Onelogin and Okta, though.

**Comment by adamstegman** [comment]
The `idp_entity_id` is fetched from the `issuer` from the SAML response: https://github.com/apokalipto/devise_saml_authenticatable/blob/5b5c9490c121eb64282955f11671f6109c484ed0/lib/devise_saml_authenticatable/default_idp_entity_id_reader.rb#L15. So it will be whatever your IdP is sending back! I haven't set this up in many IdPs so it is quite likely that different IdPs will use different values for the Issuer.

In your case, you should look at the SAML response yourself to see if there are multiple Issuers. Then you might be able to figure out what configuration to change to reduce it to 1.

Or, Ping might not be returning an Issuer at all, in which case you may need to override the `idp_entity_id_reader` [in your config](https://github.com/apokalipto/devise_saml_authenticatable#configuring-handling-of-idp-requests-and-responses) to find a different value that indicates the response is from Ping and for your application.

**Comment by liujohnson118** [comment]
Thanks for the response! 

In my case my client's IDP is offered by Ping. Unlike Okta and Onelogin, this IDP does not have a login page where you first type your email, then on another page you type your password. So I want to use a form to authenticate. 

So far I've tried
```
=form_tag(Settings.sso.idp_sso_target_url, html: {role: 'form'}, method: :post) do |f|
    .form-group
      label for="email"  Email
      = email_field_tag :email
    .form-group
      label for="password"  Password
      = password_field_tag :password
      button.btn.btn-info.btn-sm type="submit"  Submit
      | &nbsp;

``` 
where Settings.sso.idp_sso_target_url is the SSO target url that looks like `https://auth2test.clientname.ca/idp/SSO.saml2`

With Ping as IDP, I got this:

```
<S11:Envelope><S11:Body><S11:Fault><faultcode>soapenv:Client</faultcode><faultstring>Invalid Request</faultstring></S11:Fault></S11:Body></S11:Envelope>
```
Then I tested using Onelogin as IDP, it just redirected me to the page where I input my email.

I've also tried 
```
  = form_for(resource, as: resource_name, url: saml_user_session_path(resource_name), html: {role: 'form'}) do |f|
    .form-group
      label for="email"  Email
      = f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', placeholder: 'Email', id: 'email'
    .form-group
      label for="password"  Password
      = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control', id: 'password'
    button.btn.btn-info.btn-sm type="submit"  Submit
            | &nbsp;

```
This one is giving error Invalid email or password (I'm sure that's correct). 

I highly doubt that I'm on the right track. Please point me to the correct direction. Thank you very much!

**Comment by adamstegman** [comment]
This gem definitely assumes the IdP will host the login form. I'm not really sure how this approach would work. As long as the SAML response goes to `/users/saml/auth`, it ought to work once you get the initial request right.

You'll need to learn from Ping how to build the correct SAML request. Presumably, you'll need to wrap up the email and password into a SAML request using ruby-saml. Beyond that, I have no idea! I didn't know any IdPs used a workflow like this.

**Comment by liujohnson118** [comment]
I see. Thanks! Even though I haven't figured out a fix for my problems yet. But for anyone experiencing issuer assertion nodes not found: 
I found that in `ruby-saml` `lib/onelogin/ruby-saml/response.rb` around line 292 in the `issuers` method you can override `issuer_assertion_nodes = xpath_from_signed_assertion("/a:Issuer")` to `issuer_assertion_nodes = [REXML::Element.new('saml:Issuer').add_text(Your IDP Entity ID Here)]`. This will force the issuers validation to go through. You should only override when absolutely sure.
