### ISSUE TITLE
has anyone faced this warden process unauthenticated issue ?

### ISSUE THREAD

**Issue by pankajagarwal** [apokalipto/devise_saml_authenticatable#142]
I am running into a strange issue with process unauthenticated on the auth call. The setup is working fine for going to IDP and coming back with a good saml response with claims field.

here's my attribute-map.yml

`"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "email"
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "last_name"
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "first_name"`

here are the settings i am using (values scrubbed) ..

`Devise.setup do |config|

  config.saml_create_user = false
  config.saml_update_user = true
  config.saml_default_user_key = :email
  config.saml_session_index_key = :session_index
  config.saml_use_subject = false
  config.idp_settings_adapter = nil
  config.saml_route_helper_prefix = 'saml'

  config.saml_configure do |settings|
    settings.assertion_consumer_service_url     = "https://source/auth"
    settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    settings.name_identifier_format             = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
    settings.issuer                             = "https://source/metadata"
    settings.idp_name_qualifier                 = "targettrust"
    settings.idp_entity_id                      = "targetmain"
    settings.idp_slo_target_url                 = "targetmain"
    settings.idp_sso_target_url                 = "targetmain"
    settings.idp_cert                           = 'certxyz'
  end`

`INFO -- : [a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] Completed 401 Unauthorized in 24ms
F, [2019-04-20T04:34:26.456864 #67] FATAL -- : [a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02]
F, [2019-04-20T04:34:26.517668 #67] FATAL -- : [a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] NoMethodError (undefined method `flash' for #<ActionDispatch::Request:0x000055870498db00>):
F, [2019-04-20T04:34:26.517780 #67] FATAL -- : [a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02]
F, [2019-04-20T04:34:26.517854 #67] FATAL -- : [a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] devise (4.4.1) lib/devise/failure_app.rb:19:in `flash'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] devise (4.4.1) lib/devise/failure_app.rb:73:in `recall'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] devise (4.4.1) lib/devise/failure_app.rb:41:in `respond'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] actionpack (5.1.6) lib/action_controller/metal.rb:242:in `block in action'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] devise (4.4.1) lib/devise/failure_app.rb:23:in `call'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] devise (4.4.1) lib/devise/delegator.rb:7:in `call'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] warden (1.2.7) lib/warden/manager.rb:143:in `call_failure_app'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] warden (1.2.7) lib/warden/manager.rb:129:in `process_unauthenticated'
[a4cfa6d3-48a3-4637-b6b5-ef6b94a09b02] warden (1.2.7) lib/warden/manager.rb:44:in `call'`

**Comment by joshijimit** [comment]
Hi @pankajagarwal , Can you please give some details on this issue. I am also facing the same. Wondering if it could be due to my SP have self signed https certificate. I am trying the integrate Azure AD in my application through SAML. And everything looks good but at the end I have this error coming and it isn't logging into the system.

I, [2019-06-15T12:49:42.442279 #7897]  INFO -- : Processing by SamlSessionsController#create as HTML
I, [2019-06-15T12:49:42.442507 #7897]  INFO -- :   Parameters: {"SAMLResponse"=>"......"}
I, [2019-06-15T12:49:42.475821 #7897]  INFO -- : Completed 401 Unauthorized in 33ms (ActiveRecord: 1.0ms)
