### ISSUE TITLE
Does this app do SP initiated logout?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [apokalipto/devise_saml_authenticatable#147]
For this post, let's pretend I didn't do anything in https://github.com/apokalipto/devise_saml_authenticatable/issues/128.

I want to do SP initiated logout without monkey patching this gem, but my logout doesn't seem to work. I'm using version 1.4.1 of this gem, if a user does a SP initiated logout, the user are logged back in automatically, so the user can't logout.

I looked at the source code. The gem use devise to log user out locally, then creates a logout request to the IDP:

```
  # Override devise to send user to IdP logout for SLO
  def after_sign_out_path_for(_)
    idp_entity_id = get_idp_entity_id(params)
    request = OneLogin::RubySaml::Logoutrequest.new
    binding.pry
    request.create(saml_config(idp_entity_id))
  end
```

But I think maybe the above request is missing some info (please correct me if I'm wrong), because I compared it with the ruby-saml gem. ruby-saml gem's README documentation have this:
```
# Create a SP initiated SLO
def sp_logout_request
  # LogoutRequest accepts plain browser requests w/o paramters
  settings = saml_settings

  if settings.idp_slo_target_url.nil?
    logger.info "SLO IdP Endpoint not found in settings, executing then a normal logout'"
    delete_session
  else

    # Since we created a new SAML request, save the transaction_id
    # to compare it with the response we get back
    logout_request = OneLogin::RubySaml::Logoutrequest.new()
    session[:transaction_id] = logout_request.uuid
    logger.info "New SP SLO for userid '#{session[:userid]}' transactionid '#{session[:transaction_id]}'"

    if settings.name_identifier_value.nil?
      settings.name_identifier_value = session[:userid]
    end

    relayState =  url_for controller: 'saml', action: 'index'
    redirect_to(logout_request.create(settings, :RelayState => relayState))
  end
end
```
Notice that ruby-saml sets the name_identifier_value for the setting which the devise_saml_authenticatable gem doesn't do.

I think because of this, the user is not actually logged out in the IDP side, and we need to add the name_identifier_value to the setting?

Can someone please confirm that this gem's SP initiated logout only log the user out locally and does not log the user out in the IDP side and does not log the user out in other app that use the same SAML single sign on?

**Comment by Yu-Chieh-Henry-Yang** [comment]
Hi @adamstegman ,

> Interesting, I haven't seen `name_identifier_value` before. What value should it have?

In `config/devise.rb`, we have this line:
`  config.saml_default_user_key = :the_user_identifier`
which is an attribute that is used to identify the user.
I think this is the value that should be assigned to `name_identifier_value`, because it is used to identify the user.

> Is there a value from the login request that we could store in the session or on the user model?

In my system, when the user successfully logs in, the SAML response from IDP through the user's browser contains attributes about the user that has been authenticated. `the_user_identifier` is one of those attributes. And by specify this attribute in `config/attribute-map.yml`, the attribute is automatically created/saved with the user record.

When the user wants to log out, we can save the user's `the_user_identifier` attribute in a session or in an instance vairable, so that we can attach it to the SP initiated logout request that our system will create later.

> It seems like it would be IdP-specific. 

> Currently, SP-initiated log out works for us using OneLogin.

This is interesting. I thought when SP initiates logout, IDP would need to know which user to log out in their end, so they need the above attribute `the_user_identifier` to identify the user.

But as you said, OneLogin is able to logs the user out in IDP and in other SP without that piece of information. Do you know how OneLogin is able to know which user to log out without knowing the `the_user_identifier` to identify the user?

Also, I saw that in ruby-saml gem's README (https://github.com/onelogin/ruby-saml#single-log-out), that they have the `name_identifier_value` in their SP initiated logout request, so I was expecting that we need it to do SP initiated logout. But as you have mentioned above, OneLogin works without it.

**Comment by Yu-Chieh-Henry-Yang** [comment]
I think I have found my answer here: https://stackoverflow.com/questions/11693297/what-are-the-different-nameid-format-used-for

I think the current implementation of this gem and OneLogin is using transient name ID while my IDP is using unspecified name id.

So yes, I think you are right that I have this difference in behaviour because our IDP behave differently.

**Comment by Yu-Chieh-Henry-Yang** [comment]
I think it's a good time to introduce https://github.com/apokalipto/devise_saml_authenticatable/issues/128 again.

Yes, I have implemented it already with my IDP, the changes are specified in https://github.com/apokalipto/devise_saml_authenticatable/issues/128 again.

**Comment by Yu-Chieh-Henry-Yang** [comment]
@adamstegman 
No worries! i tried to push a branch to this repo so that I can create a pull request, but I don't seem to have the access right to do so. Can you add me as one of the collaborator in this project?

**Comment by Yu-Chieh-Henry-Yang** [comment]
I see, thanks for the explanations.
The PR is here: https://github.com/apokalipto/devise_saml_authenticatable/pull/149

**Comment by Yu-Chieh-Henry-Yang** [comment]
Hi @adamstegman ,
I try to run the test on master which should be working code, but the RSpec failed:
Launched sp on port 8020 (pid 80570)...
      creates a user on the SP from the IdP attributes (FAILED - 23)

Do you know how I can setup the spec properly?

**Comment by adamstegman** [comment]
You shouldn't run the specs from `spec/support/sp` or `spec/support/idp`; those apps are generated during integration testing by the gem. You may need to remove those folders before running all the tests so rake doesn't think they need to be run as well.
