### ISSUE TITLE
What is the ACS URL?

### ISSUE THREAD

**Issue by cagedartist** [apokalipto/devise_saml_authenticatable#15]
In the documentation, this example is given:

assertion_consumer_service_url: "http://localhost:3000/users/sign_in"

But /users/sign_in does not exist. I tried /users/saml/auth, but that redirects in a loop because the user is never logged in locally.

**Comment by cagedartist** [comment]
Okay, I got it: /users/saml/auth is correct -- just a documentation issue. 

The reason it looped for me is the user wasn't found (and preference was not to create). The failure redirected to the root path, which requires sign-in, so back out to the IdP, then back to the ACS, repeat.

Thanks for the gem, BTW. I like it much better than using omniauth and omniauth_saml.

**Comment by adamstegman** [comment]
> The reason it looped for me is the user wasn't found (and preference was not to create). The failure redirected to the root path, which requires sign-in, so back out to the IdP, then back to the ACS, repeat.

Yeah, that happened to us too. We configured a `Devise::FailureApp` that detects an `:invalid` warden response and renders an error page, or calls `super` otherwise.

**Comment by apokalipto** [comment]
I just updated the documentation. I am going to close this issue! Thanks for pointing it out.
