### ISSUE TITLE
/users/saml/auth path does not exist

### ISSUE THREAD

**Issue by phil-plencner-hl** [apokalipto/devise_saml_authenticatable#154]
I'm attempting to get the SAML Authentication working using an existing ldP.

I have set up the /config/initializers/devise.rb file with configuration settings to my specific ldP.

The paths for /users/saml/sign_in and /users/saml/metadata both currently exist.

In fact, I can go to /users/saml/sign_in and see my authentication page. After logging in successfully, the ldP sends me to /users/saml/auth.....but that page does not exist.

What can I do to add this route/page to my site? 

Unfortunately the site is behind a firewall so I cannot send specific links to it.

**Comment by adamstegman** [comment]
Your routes should include a `devise_for` line or block, can you include that? It may also be helpful to include the output of `bin/rails routes | grep saml`.

**Comment by phil-plencner-hl** [comment]
Hello,

I was able to update my routes file to include this, which made the route work correctly! Thanks!

    devise_for :users
      devise_scope :user do
        scope "users", controller: 'devise/saml_sessions' do
          get :new, path: "saml/sign_in", as: :new_user_sso_session
          post :create, path: "saml/auth", as: :user_sso_session
          get :destroy, path: "sign_out", as: :destroy_user_sso_session
          get :metadata, path: "saml/metadata", as: :metadata_user_sso_session
          match :idp_sign_out, path: "saml/idp_sign_out", via: [:get, :post]
        end
    end
