### ISSUE TITLE
Metadata Import Error md namespace prefix

### ISSUE THREAD

**Issue by kcollignon** [apokalipto/devise_saml_authenticatable#157]
Hi there,

My Idp is stating that when they are importing the metadata file in to their system it is producing an invalid XML error. Would you happen to know what causes this? They are using ADFS. Thanks

`XML Parsing Error on Line 15
Namespace prefix md on AssertionConsumerService is not defined`

**Comment by adamstegman** [comment]
Interesting. I'm not super up on my XML parsing, but it looks like the `md` namespace should be defined. On my app, the `md:EntityDescriptor` tag has a `xmlns:md='urn:oasis:names:tc:SAML:2.0:metadata'` property.

Regardless, we delegate this task to the `ruby-saml` gem: https://github.com/apokalipto/devise_saml_authenticatable/blob/2105b89e2117ce6e0761c577ea6a810931295b31/app/controllers/devise/saml_sessions_controller.rb#L23-L24

This is where the ruby-saml gem defines the `md` namespace: https://github.com/onelogin/ruby-saml/blob/5f9dcd9a010126a7378edfd554722edb887c3060/lib/onelogin/ruby-saml/metadata.rb#L23

I'm not sure what else we could do. Could you provide your metadata document (feel free to obscure any sensitive info, like URLs)? We can double-check that it looks alright. Maybe there's an XSD somewhere for that namespace that you can provide them with.

**Comment by kcollignon** [comment]
@adamstegman  thanks for the speedy response. I think it was an issue with the Idp as I updated the signing certificate and then they said they could import the metadata just fine  🤷‍♂ 

However they are now  saying that the SAML request is having an error. I think I have everything configured properly on my end. Would this error denote a config issue on the Rails end?

`The SAML protocol message cannot be read because it contains data that is not valid. ---> System.UriFormatException: Invalid URI: The URI is empty.`

`the saml:AuthnContextClassRef attribute is empty`

**Comment by kcollignon** [comment]
Sorry, I spoke too soon. Looks like this Idp required me to set the `authn_context` parameter in the settings and it worked. Thanks

**Comment by mattbaumann1** [comment]
We are experiencing an issue with the IDP loading the metadata XML on a new instance. It looks the same to me as our other instances that load fine. I am wondering if we might need to set the `authn_context`. What type of values go in here? We haven't had to use this before. Also below is the error that the IDP is experiencing. 
```
2020-06-11 13:42:00,388 - ERROR [org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver:462] - Metadata Resolver FilesystemMetadataResolver competitionStageMetadata: Unable to unmarshall metadata: net.shibboleth.utilities.java.support.xml.XMLParserException: Unable to parse inputstream, it contained invalid XML
```

**Comment by mattbaumann1** [comment]
I thought I would follow up. For us we needed to change the security settings. We were having trouble because we did not have want_assertion_signed (ruby-same) set to true.
