### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by mattbaumann1** [apokalipto/devise_saml_authenticatable#169]
Currently, we are pulling from GitHub instead of through rubygems because we need the sp initiated logout and that functionality hasn't been updated there. 

I was wondering if there was a plan to have a new release soon, since the last one was 1 1/2 years ago. 

If not, I would encourage you to update the readme to pull from this repo instead of simply using.
```
gem 'devise_saml_authenticatable'

**Comment by adamstegman** [comment]
I haven't gotten a response from @apokalipto so I'll email him again. Updating the README is a good idea, but kind of a bummer!
