### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by luke-zhou** [apokalipto/devise_saml_authenticatable#171]
Hi, 
May I ask whether there is a plan to release version 1.6.0 to rubygems.org? I really want to use the new multi IdPs feature in the version.
Thanks

**Comment by adamstegman** [comment]
Unfortunately, @apokalipto is the only person with permission to release a new version. I've updated the instructions in the README to reference GitHub directly until he has had a chance to do so.

**Comment by apokalipto** [comment]
I just released version 1.6.

Sorry for the delay.
