### ISSUE TITLE
Action metadata is not fully supporting multi IdPs

### ISSUE THREAD

**Issue by luke-zhou** [apokalipto/devise_saml_authenticatable#173]
Because there is no idp_entity_id passed into this action, the XML file doesn't display the correct information. 
```
  def metadata
    meta = OneLogin::RubySaml::Metadata.new
    render :xml => meta.generate(saml_config)
  end
```
The easiest way to fix that would be appending a parameter idp_entity_id in the URL. Happy to create a PR if that is the case.

**Comment by adamstegman** [comment]
That would definitely work. 👍🏼
