### ISSUE TITLE
Completed 401 Unauthorized - How to Debug?

### ISSUE THREAD

**Issue by victorlcampos** [apokalipto/devise_saml_authenticatable#180]
Hi,
I'm facing Completed 401 Unauthorized in a client and don't know how to debug it.

Someone can help me to giving ideias on How to Debug?

Here the XML of the response:
https://gist.github.com/victorlcampos/c5c2604477d4796fc021516249fdc6fd

**Comment by adamstegman** [comment]
Hi! There's a couple log messages for common issues:

- "Auth errors": https://github.com/apokalipto/devise_saml_authenticatable/blob/09221d59e434bc947327e478a388013a70add4f7/lib/devise_saml_authenticatable/strategy.rb#L43
    - This indicates the SAML response was not valid with your configuration, and suggests a configuration issue, either in your SP or in your IdP.
- "Resource could not be found": https://github.com/apokalipto/devise_saml_authenticatable/blob/09221d59e434bc947327e478a388013a70add4f7/lib/devise_saml_authenticatable/strategy.rb#L50
    - This means the user wasn't found, so it's possible the wrong attribute is being used to look up the user, or just that they need to be created by setting `Devise.saml_create_user = true`.

You can also set `Devise.saml_failed_callback` to a class that has a `#handle(saml_response, strategy)` method, and inspect the response and strategy yourself for problems.

**Comment by victorlcampos** [comment]
Thanks
