### ISSUE TITLE
Guidance on saml_failed_callback redirect

### ISSUE THREAD

**Issue by hlascelles** [apokalipto/devise_saml_authenticatable#182]
The documentation says:

```
You can set a handler object that takes the response for a failed SAML request and the strategy,
and implements a #handle method. This method can then redirect the user, return error messages, etc.
config.saml_failed_callback = nil
```
We would like to redirect the user, but we can't see how at that point. We don't have access to the Rails `request` to call `redirect_to`. Could you give an example of how to redirect a user to an error page in that handler? Thanks!

**Comment by adamstegman** [comment]
The integration tests are calling `redirect!` on the strategy: https://github.com/apokalipto/devise_saml_authenticatable/blob/09221d59e434bc947327e478a388013a70add4f7/spec/support/sp_template.rb#L51. I haven't looked at that in quite a while myself, but does that work for you?

**Comment by hlascelles** [comment]
Aha, yes that works perfectly, thank you!
