### ISSUE TITLE
OneLogin::RubySaml::ValidationError (Issuer of the Assertion not found or multiple.)

### ISSUE THREAD

**Issue by teksetter** [apokalipto/devise_saml_authenticatable#189]
Hello,
after entering the configuration of my environment in devise.rb, when I try to log in I get the message:

> An OneLogin::RubySaml::ValidationError occurred in saml_sessions#create:
> 
>   Issuer of the Assertion not found or multiple.
> 
> [56d0c48f-cec3-43fb-ae89-bebb47a72703] OneLogin::RubySaml::ValidationError (Issuer of the Assertion not found or multiple.):
> [56d0c48f-cec3-43fb-ae89-bebb47a72703]
> [56d0c48f-cec3-43fb-ae89-bebb47a72703] ruby-saml (1.11.0) lib/onelogin/ruby-saml/response.rb:295:in `issuers'
> [56d0c48f-cec3-43fb-ae89-bebb47a72703] devise_saml_authenticatable (1.6.3) lib/devise_saml_authenticatable/default_idp_entity_id_reader.rb:15:in `entity_id'

in devise.rb:

> config.saml_configure do |settings|
>     settings.assertion_consumer_service_url = 'https://**********//saml/auth'
>     settings.assertion_consumer_service_binding = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
>     settings.protocol_binding                   = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
>     settings.name_identifier_format = 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
>     settings.sp_entity_id           = 'https://**********//saml/metadata'
>     settings.idp_slo_target_url = 'https://**********//saml/idp_sign_out'
>     settings.idp_sso_target_url = 'https://**********/idp/profile/SAML2/Redirect/SSO'
>     settings.certificate                        = APP_CONFIG['saml_cert']
>     settings.private_key                        = APP_CONFIG['saml_key']
>     settings.idp_cert_fingerprint_algorithm     = 'http://www.w3.org/2000/09/xmldsig#sha1'
>     settings.security[:authn_requests_signed]   = false
>     settings.security[:logout_requests_signed]  = false
>     settings.security[:logout_responses_signed] = false
>     settings.security[:metadata_signed]         = false
>     settings.idp_cert_fingerprint               = APP_CONFIG['cert_fingerprint']
>   end

but i can't troubleshoot.

In the log the euth request seems correct:

> D, [2021-01-14T11:17:26.074382 #369830] DEBUG -- : Created AuthnRequest: 
> <samlp:AuthnRequest AssertionConsumerServiceURL='https://********/saml/auth' Destination='https://********/idp/profile/SAML2/Redirect/SSO' ID='_97422a85-b3fc-4817-866f-b1a3240591e6' IssueInstant='2021-01-14T10:17:26Z' ProtocolBinding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'>
> 	<saml:Issuer>https://********/saml/metadata</saml:Issuer>
> 	<samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:2.0:nameid-format:transient'/>
> </samlp:AuthnRequest>

in the <saml2p:Response ... > i found 

> <saml2p:Status>
>     <saml2p:StatusCode Value='urn:oasis:names:tc:SAML:2.0:status:Responder'/>
>     <saml2p:StatusMessage>An error occurred.</saml2p:StatusMessage>
> </saml2p:Status>

that doesn't help me understand the mistake

is there anyone who could help me understand the error?

Thank you all

Giuseppe

**Comment by adamstegman** [comment]
Debugging IdP error is always difficult, they don't really give you anything to work with. It may be quicker to ask your IdP to give you more error information.

Some things I noticed that may or may not be the issue:

- `assertion_consumer_service_url` is missing `/users/` in the middle, it should be `https://**********/users/saml/auth`
- `sp_entity_id` is also missing `/users/`, it should be `https://**********/users/saml/metadata`
- `certificate` and `private_key` are set, is your IdP configured to decrypt that signature? I notice you have signatures turned off in a few places, not sure if that covers everything or not. Might be easier to remove those settings instead.
- `idp_slo_target_url` should be a path at your IdP to sign the user out, similar to `idp_sso_target_url`, but that shouldn't cause any issues with login

**Comment by teksetter** [comment]
I solved it, the problem was related to the certificate used to sign the request and why I didn't set the _want_assertions_encrypted_ parameter
