### ISSUE TITLE
Validating `InResponseTo` attribute?

### ISSUE THREAD

**Issue by nholden** [apokalipto/devise_saml_authenticatable#194]
👋 Hi there! New user of `devise_saml_authenticatable` here. Thanks for the great project!

It looks like `devise_saml_authenticatable` doesn't support validating the `InResponseTo` attribute in SAML assertions. The `InResponseTo` attribute associates a given assertion to a given authentication request, and according to the [SAML 2.0 CORE specification](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) (section 3.2.2), it's required in any SAML response generated in response to a request.

`ruby-saml` [will validate the `InResponseTo` attribute](https://github.com/onelogin/ruby-saml/blob/b55733fd64a559de81ad936b69cd1e9b754c40a8/lib/onelogin/ruby-saml/response.rb#L594-L606) for us if we pass `OneLogin::RubySaml::Response` a `matches_request_id` parameter when we initialize it. `devise_saml_authenticatable` is not currently doing that when we [parse a SAML response](https://github.com/apokalipto/devise_saml_authenticatable/blob/5c9008e8ca542cc84a03d71586f1161ddd08a23d/lib/devise_saml_authenticatable/strategy.rb#L37-L41).

If we could persist an ID [generated for a SAML request](https://github.com/apokalipto/devise_saml_authenticatable/blob/5c9008e8ca542cc84a03d71586f1161ddd08a23d/app/controllers/devise/saml_sessions_controller.rb#L16) and include that ID in the `matches_request_id` parameter when we initialize the `OneLogin::RubySaml::Response` when we receive the SAML response back from the identity provider, it seems like we could take advantage of the `InResponseTo` validation built into `ruby-saml`. This line from the `ruby-saml` README makes me think it might be possible to persist that ID in the user's session:

>     logout_response = OneLogin::RubySaml::Logoutresponse.new(params[:SAMLResponse], settings, :matches_request_id => session[:transaction_id])

As someone new to `devise_saml_authenticatable`, I'm curious...
1. Does it make sense for `devise_saml_authenticatable` to support validating the `InResponseTo` attribute in SAML assertions?
2. Does it seem feasible to persist SAML request IDs in the user's session?

Thanks again! Let me know if there's anything I can clarify.

**Comment by adamstegman** [comment]
Thanks for pointing this out! This seems like a great idea. I'm interested in how it relates to `RelayState`, since they seem like they're solving the same problem (see #63), but since both are supported by IdPs it would make sense to support both on the application side.

My only hesitation is that since it's new functionality and some IdPs may not be conformant, it should probably be opt-in. I'll also need to dig into Warden's API and make sure that we have access to the session in the strategy.

**Comment by nholden** [comment]
Thanks, @adamstegman! Glad to hear this is something you think `devise_saml_authenticatable` could support.

I can take a first pass at looking into the relationship between `InResponseTo` and `RelayState` and whether we have access to the session. If it makes sense and would be helpful, I can also take a first stab at a PR that lets folks opt-in.

**Comment by adamstegman** [comment]
That would be great! Unfortunately I can't devote a lot of time to this gem. I did add the `matches_request_id` parameter and use the session to store it, and the integration specs still run just fine, so I think we're all set to add this feature.

**Comment by nholden** [comment]
I took a stab at this in https://github.com/apokalipto/devise_saml_authenticatable/pull/195!
