### ISSUE TITLE
Logging of reason for fail of strategy is hardcoded to debug level

### ISSUE THREAD

**Issue by tkalliom** [apokalipto/devise_saml_authenticatable#207]
We encountered some issues in authentication where it would have been helpful to see from our production log why authentication was refused. At the moment, logging of the reason for the strategy failing is done with `DeviseSamlAuthenticatable::Logger.send`, which is hardcoded to use the level `0` (`Logger::DEBUG`).

I would be willing to make a PR. There are a couple of possible customization points – which should be used?
* A configuration variable `saml_log_level` which `DeviseSamlAuthenticatable::Logger` uses, defaulting to `0`
* A configuration variable `saml_logger` which `Devise::Strategies::SamlAuthenticatable` uses, defaulting to `::DeviseSamlAuthenticatable::Logger`

Somewhat related is `Devise::Models::SamlAuthenticatable` calling `logger.info`, but I guess that can be customized by implementing your own `authenticate_with_saml`?

**Comment by adamstegman** [comment]
I'm not sure it makes sense to use a separate logger from Rails, or a single level everywhere. What about modifying `DeviseSamlAuthenticatable::Logger` to support multiple levels and using higher levels in some key places?
