### ISSUE TITLE
Encrypted authentication request support limitation

### ISSUE THREAD

**Issue by mordocai** [apokalipto/devise_saml_authenticatable#21]
My company is currently looking at using this gem for an upcoming project of ours.

Is anyone currently working on an implementation of authentication request encryption?

I don't yet know much about SAML, but I assume not having the request encrypted is a security issue when connecting across the Internet to a third-party SAML provider?

If no one is working on this and it is a security issue my team may end up needing to implement this and would want to cooperate with upstream(you). If this becomes the case, having some guidance on how upstream would like this implemented would be very helpful.

**Comment by mordocai** [comment]
For what it is worth, I see the previous issue where the issuer was directed to ruby saml but it appears that they support encrypted requests. See: https://github.com/onelogin/ruby-saml/issues/230

**Comment by apokalipto** [comment]
Hi mordocai,

ruby-saml now supports request signature and encryption. We will include this functionality in the future. For the moment there is no urgent need to include it. ¿Maybe you can help?

The security concern is valid when you intend to use third party IdPs. When your application issues a request, the IdP has to make the decission wheater the request is valid or not. using SSL will protect the request (encrypting it would be an extra layer of security). Signing the request would be the best way to determine the validity of the sender.

I haven't dig much into the details on how to implement the request signature and/or encryption. I am pretty sure this is a set of settings that should be passed to `OneLogin::RubySaml::Settings`. Take a look a the documentation of ruby-saml in the Signing section. Give it a try by including those parameters in the idp.yaml file. It might just work!

Cheers

**Comment by mordocai** [comment]
Sounds good. We're still in the planning stage so it might be a while (We're working with US government on some of this so it takes awhile to make decisions) but we'll definitely look into it when we get to the point of actually writing some code for the SAML integration of our product.

Thank you!

**Comment by mathieujobin** [comment]
does request encryption been implemented? I saw this PR https://github.com/apokalipto/devise_saml_authenticatable/pull/24 but that does not look to be enough? or is it ? 

what are the advantage of this gem over omniauth-saml ?
it would be great to have a comparison posted somewhere, I cannot find anything exhaustive on the subject

thank you

**Comment by adamstegman** [comment]
#24 should be enough to configure ruby-saml with a private key for encryption. I haven't set that up myself so I'm not sure of the process.

Frankly I've never used omniauth so it's hard for me to compare the libraries. I'd be happy to incorporate a comparison if you want to write one up.

**Comment by mathieujobin** [comment]
thank you for both of your answers @adamstegman
