### ISSUE TITLE
NoMethodError (undefined method `session_index=' for #<User>

### ISSUE THREAD

**Issue by rakaur** [apokalipto/devise_saml_authenticatable#228]
I've seen a ton of "can't log out from IdP" posts but they all seem to require code changes and all seem to work in different ways and there doesn't seem to be a "correct solution"? The title is the error that I get when I try to sign out from the IdP. I have `config.saml_session_index_key = :session_index` but I'm apparently supposed to do more things to get this to actually work? Is that supposed to be a database field? But if you store it in the db it will change and invalidate, according to other tickets. So I'm not sure what I'm supposed to do here. I want logging out from the IdP to work. Right now, it does not, and I do not know what I am supposed to do to change that.

**Comment by adamstegman** [comment]
That's right, `session_index` should be a column in your `users` table. Logout from the IdP will then change that value to invalidate the session.
