### ISSUE TITLE
Wiki Page edit/

### ISSUE THREAD

**Issue by rylanb** [apokalipto/devise_saml_authenticatable#229]
On this page: https://github.com/apokalipto/devise_saml_authenticatable/wiki/Setting-Up-with-Multiple-Providers

It says For a bare bones setup you must require: idp_slo_target_url idp_cert_fingerprint idp_entity_id #

But i THINK that it should be idp_sso_target_url? I think the slo is the sign out. I am basing that on: https://github.com/apokalipto/devise_saml_authenticatable/issues/189 where it shows a url for that value as a sign out url plus locally when trying to setup multiple providers it is saying 'sso target url required' or something like that. 

I am not sure the recommended way to edit a wiki page and I didn't want to click 'edit page' if I'm wrong here. 

Thanks for putting this gem together and I hope this is helpful!

**Comment by adamstegman** [comment]
Thanks for pointing this out! Feel free to edit the page, I think you're right about that typo.

**Comment by rylanb** [comment]
Ok great thanks! Didn't want to go willy nilly editing things w/o checking in 1st.

https://github.com/apokalipto/devise_saml_authenticatable/wiki/Setting-Up-with-Multiple-Providers updated now. I tried to standard formatting / language and add comments. Let me know if that is too much! Thanks again!
