### ISSUE TITLE
Requesting new gem version release

### ISSUE THREAD

**Issue by siasmj** [apokalipto/devise_saml_authenticatable#232]
Hi there! I would like to request a new version of the gem be released, if possible.

I was testing an app that uses devise_saml_authenticatable version 1.9.0 for compatibility with Ruby 3.2 and ran into an exception. In version 1.9.0, `lib/devise_saml_authenticatable/saml_config.rb` calls the `File.exists?` method, which was deleted in Ruby 3.2. I saw this is fixed in master by #223. Normally, I would just install the gem from the master branch until a new version of the gem was released. But, in this case, I have a gem that uses devise_saml_authenticatable as a runtime dependency. As far as I can tell, gem runtime dependencies can only resolve to RubyGems and not other sources like GitHub.

Thank you for your consideration and for providing this gem!

**Comment by adamstegman** [comment]
You got it! I guess I left that sitting for a long time. Published v1.9.1 now.

* [Release page](https://github.com/apokalipto/devise_saml_authenticatable/releases/tag/v1.9.1)
* [Gem page](https://rubygems.org/gems/devise_saml_authenticatable/versions/1.9.1)
