### ISSUE TITLE
When there is a key with multiple values in the `SamlMappedAttributes` the `attribute_value_by_resource_key` method only return the first value

### ISSUE THREAD

**Issue by morissetcl** [apokalipto/devise_saml_authenticatable#239]
Hi there,

I use the gem with Google as provider and I try to retrieve for a user the associated `groups` that are set up on the workspace.

The `SamlMappedAttributes` that I receive look like this.
```
#<SamlAuthenticatable::SamlMappedAttributes:0x0000ffff7e2ac280 @attributes=#<OneLogin::RubySaml::Attributes:0x0000ffff7e1b4a30 @attributes={"email"=>["john@mail.com"], "employee_id"=>[], "first_name"=>["John"], "last_name"=>["Hean"], "organization"=>[], "organization_unit_path"=>["/allUsers"], "groups"=>["Finance", "HR"]}>, @attribute_map={"email"=>"email", "last_name"=>"last_name", "groups"=>"groups"}>
````

But when I use `.attribute_value_by_resource_key` to fetch the groups  this method only return the first value of the array rather than the whole value of the key.

```
saml_response.attribute_value_by_resource_key("groups")
=> "Finance"
```

I looked into the [spec](https://github.com/apokalipto/devise_saml_authenticatable/blob/f70ece1f1feebe9e825afc0098274792223b9421/spec/devise_saml_authenticatable/saml_mapped_attributes_spec.rb#L4), tried to pass an array of multiple values and it returns correctly the array.  

I don't understand why  I have this behaviour. is it intended? Any ideas?
Thanks

**Comment by adamstegman** [comment]
@morissetcl this is actually a feature of ruby-saml, which only returns the first value: https://github.com/SAML-Toolkits/ruby-saml/blob/c9685a98a9c00c38af65364e70a7315eb49a2222/lib/onelogin/ruby-saml/attributes.rb#L11-L14.

It looks like you can set `OneLogin::RubySaml::Attributes.single_value_compatibility = false` to disable this behavior.

**Comment by morissetcl** [comment]
Sounds good! Thanks!
