### ISSUE TITLE
Is there a way to support multiple authn_context values from a single IdP?

### ISSUE THREAD

**Issue by drsharp** [apokalipto/devise_saml_authenticatable#241]
The readme specifies:
```
settings.authn_context = ""
```
which implies a single value for the `authn_context` but it looks like SAML itself supports multiple values as best I can understand. But I don't see how this gem can support multiple `authn_context` values for a given IdP?

Is there something I'm missing perhaps?

**Comment by adamstegman** [comment]
The settings are configured in [`ruby-saml`](https://github.com/SAML-Toolkits/ruby-saml), whose README does state it can be an array:

```
  # Optional for most SAML IdPs
  settings.authn_context = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
  # or as an array
  settings.authn_context = [
    "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
    "urn:oasis:names:tc:SAML:2.0:ac:classes:Password"
  ]
```

If there's something this gem should do in particular to support that feature, that makes sense—I'm not familiar with it, so I don't know that would be!

**Comment by drsharp** [comment]
Adam, that makes sense. Thank you! I didn't see that bit in ruby-saml so thanks for calling that to my attention. Cheers!
