### ISSUE TITLE
:1st_place_medal: Just wanted to say "Thank you"

### ISSUE THREAD

**Issue by DavertMik** [apokalipto/devise_saml_authenticatable#242]
Thanks so much, @apokalipto 

SAML is a dead complicated thing and I would not make it alone without your gem. At first I was skeptical integrating SAML into my app but customers insisted on SSO more and more. I tried providers like Auth0 but their bills became crazy for enterprise connections. So I looked into other alternatives and even ruby-saml was there I could not start with it. 

Thanks for devise+saml integration! :heart:

**Comment by apokalipto** [comment]
You're welcome! I am glad that this gem turned out to be useful, although much of the great work has been actually done and overseen by @adamstegman 

Cheers!
