### ISSUE TITLE
Allow multiple sessions per user

### ISSUE THREAD

**Issue by codez** [apokalipto/devise_saml_authenticatable#253]
The SAML session index is required to perform an IDP-initiated logout and is used as authenticatable salt. Currently, this session index is stored directly on the user model. 

When the user logs in on a second device (or second browser, incognito window, ...), the session index of the primary device is overridden. This approach has the following problems:

- The primary device cannot be logged out through the IDP anymore.
- Because the authenticatable salt does not match the value stored in the session, Devise cannot fetch the user from the session anymore, causing 401s on the primary device for any subsequent requests. So this basically terminates the session on the primary device.

This behavior was already described in https://github.com/apokalipto/devise_saml_authenticatable/issues/151#issuecomment-540759920 and probably in other issues, but I have not found a dedicated issue just for this.

In our specific application, users could even end up in automatic login loops, when they log into a secondary devise. The JS frontend has a polling request that would get the 401 as described above (for the primary devise) and then redirect to the SAML login page. Because the IDP SAML session is still active, this directly redirects back to the application SessionController create, where a new session index is persisted in the user model. Now the secondary device gets the 401 and redirects to the SAML login, persisting another session index, and so on.

Our users switch regularly between workstations and/or mobile devices, so multiple active sessions per user is a must.

We currently solved the problem by patching this gem, removing the session index column on the user model, removing the usage of the session index as authenticatable salt and storing the session index in the Rack session only to be used for IDP logout. 

I am not that deep into Devise to decide how important it is to really use an authenticatable salt. If you think it could be left out as well, I would be happy to extract our patches as a pull request, so that the session index would only be stored in the session but not in the user model.

What do you think? Did you come up with other ways to tackle this issue?

**Comment by adamstegman** [comment]
I haven't really dug into devise in a long time, but [searching its code](https://github.com/search?q=repo%3Aheartcombo%2Fdevise%20authenticatable_salt&type=code) yields only one usage of `authenticatable_salt`, for rememberable. It should be fine to stop using this value for that—it'll be a breaking change, but it seems odd to use rememberable along with SAML authentication. We can tell people to use `remember_token` instead for that module.

So a PR would be helpful! Thank you for opening this.

**Comment by codez** [comment]
Beware, the search results collapses two more matches, where the authenticatable_salt is used to serialize a user from/to the session: https://github.com/heartcombo/devise/blob/72884642f5700439cc96ac560ee19a44af5a2d45/lib/devise/models/authenticatable.rb#L229

I will try to put a PR together in the next days.
