### ISSUE TITLE
Update the code with the improvements done on ruby-saml-example (For example SLO).

### ISSUE THREAD

**Issue by pitbulk** [apokalipto/devise_saml_authenticatable#28]
Hi Josef,

I'm one of the maintainers of the [ruby-saml](https://github.com/onelogin/ruby-saml) gem.

Time ago I improved the [ruby-saml-example](https://github.com/onelogin/ruby-saml-example) app that is a simple RoR app that uses the ruby-saml gem.

If you interested I can help you to apply the updates to the work you have done in this repository using the device strategy.

Review the improvements on SLO support:
https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L45

Also you can remove the limitation that you placed on the README:
```
The Authentication Requests (from your app to the IdP) are not signed and encrypted
```
ruby-saml 1.0.0 supports signature & decrypt. You only need to place the public cert  private key as described here: https://github.com/onelogin/ruby-saml#signing and here: https://github.com/onelogin/ruby-saml#decrypting

**Comment by apokalipto** [comment]
Hi pibulk, sorry for the delayed response! I just updated the documentation as you mentioned. Thanks for that. Feel free to help us with the changes you mention.
