### ISSUE TITLE
SAML settings based on runtime variables (like subdomain, IP address, etc)?

### ISSUE THREAD

**Issue by bmorton** [apokalipto/devise_saml_authenticatable#29]
The `ruby-saml` [example application suggests](https://github.com/onelogin/ruby-saml-example/blob/master/app/models/account.rb#L4) that the RubySaml::Settings could be retrieved during runtime such that you could support different SAML settings for different tenants.

Has anyone tried this or know where I should start poking around?

**Comment by sporto** [comment]
+1 we have exactly this use case

**Comment by rsl** [comment]
any word/update on how this worked for you guys? i'm doing same and am just overriding the Devise SAML sessions controller and specifically saml_config method to load from DB. is it that simple? any hiccups?

**Comment by adamstegman** [comment]
Overriding `saml_config` is an interesting idea. onelogin/ruby-saml#165 also suggests overriding the Settings class to accept multiple IdP settings, which could work in concert with overriding `saml_config`.

I'm going to close this issue now since it's been inactive for a while.
