### ISSUE TITLE
Completed 401 Unauthorized in 60ms

### ISSUE THREAD

**Issue by aaani** [apokalipto/devise_saml_authenticatable#32]
I am using the default setup as shown in the documentation but I am getting the following error in my app:
```
Completed 401 Unauthorized in 60ms
```
Everything is good on my IDP service's end. It authenticates the user successfully and posts response to /saml/consume route. In console I can see that it's sending the appropriate data
```
#<OneLogin::RubySaml::Attributes:0x007ffa9acd1990 @attributes={"LastName"=>["Mishra"], "FirstName"=>["Ani"], "EmailAddress"=>["anirvana@xyzemail.me"]}>
```
My attibute-map.yml looks like this:
```
  # attribute-map.yml
  "EmailAddress": "email"
  "LastName": "last_name"
  "FirstName": "first_name"
```
and user is created/updated with above attributes properly in **mongodb** via **mongoid**.

In my /saml/consume route I redirect the user to /business (which has the devise's default authenticate_user before_filter) and this where I get the 401 status.

I am using rails-4.2.4, devise-3.4.1, devise_saml_authenticatable-1.2.1 and mongoid-5.0.0

Any kind of help in debugging this is appreciated. Thanks!

**Comment by adamstegman** [comment]
Could you share your devise routes and your SAML setup from the devise initializer? I'm wondering what your `/saml/consume` route is and if anything in your config might affect this.

**Comment by aaani** [comment]
Routes:
```
                                             root GET    /                                                            home#index
                                 new_user_session GET    /users/sign_in(.:format)                                     sessions#new
                                     user_session POST   /users/sign_in(.:format)                                     sessions#create
                             destroy_user_session GET    /users/sign_out(.:format)                                    sessions#destroy
                                    user_password POST   /users/password(.:format)                                    devise/passwords#create
                                new_user_password GET    /users/password/new(.:format)                                devise/passwords#new
                               edit_user_password GET    /users/password/edit(.:format)                               devise/passwords#edit
                                                  PATCH  /users/password(.:format)                                    devise/passwords#update
                                                  PUT    /users/password(.:format)                                    devise/passwords#update
                                     saml_consume POST   /saml/consume(.:format)                                      home#saml_service_endpoint
                                       businesses GET    /businesses(.:format)                                        businesses#index

```

SAML setup in devise initializer. (Had to anonymize some paths, sorry) 
```ruby
    # Create user if the user does not exist. (Default is false)
    config.saml_create_user = true

    # Update the attributes of the user after a successful login. (Default is false)
    config.saml_update_user = true

    # Set the default user key. The user will be looked up by this key. Make
    # sure that the Authentication Response includes the attribute.
    config.saml_default_user_key = :email

    # Optional. This stores the session index defined by the IDP during login.  If provided it will be used as a salt
    # for the user's session to facilitate an IDP initiated logout request.
    config.saml_session_index_key = :session_index

    # You can set this value to use Subject or SAML assertation as info to which email will be compared
    # If you don't set it then email will be extracted from SAML assertation attributes
    config.saml_use_subject = true

    # Configure with your SAML settings (see [ruby-saml][] for more information).
    config.saml_configure do |settings|
      settings.issuer                             = "https://XXXXXXXX/saml/metadata"
      settings.assertion_consumer_service_url     = "https://XXXXXXXX/saml/consume"
      settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
      settings.name_identifier_format             = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
      settings.issuer                             = "https://XXXXXXXX"
      # settings.authn_context                      = ""
      settings.idp_slo_target_url                 = "https://XXXXXXXX/idp/SingleLogoutService"
      settings.idp_sso_target_url                 = "https://XXXXXXXX/idp/login"
      settings.idp_cert                           = "XXXXXXXX"
```

In home_controller.rb
```ruby
  def saml_service_endpoint
    redirect_to "business/"
  end
```

**Comment by adamstegman** [comment]
So what does `/saml/consume` do? It looks from your routes like `/users/sign_in` is the path that creates a user session.

**Comment by aaani** [comment]
My IDP is hardcoded to post SAML repose to /saml/consume, that's why I had to create that route. I thought devise_saml_authenticatable takes care of creating a user session. Is this not the case?

**Comment by adamstegman** [comment]
It does. But that functionality is built into the SamlSessionsController included in the gem—your IdP response should go there.

By default, if you have `app/models/user.rb` with:

```
class User < ActiveRecord::Base
  devise :saml_authenticatable
end
```

and `config/routes.rb with:

```
Rails.application.routes.draw do
  devise_for :users
end
```

you get the following routes:

```
         new_user_session GET      /users/saml/sign_in(.:format)      devise/saml_sessions#new
             user_session POST     /users/saml/auth(.:format)         devise/saml_sessions#create
     destroy_user_session DELETE   /users/sign_out(.:format)          devise/saml_sessions#destroy
    metadata_user_session GET      /users/saml/metadata(.:format)     devise/saml_sessions#metadata
idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format) devise/saml_sessions#idp_sign_out
```

And the IdP response should go to `/users/saml/auth`. Note that the controller that route points to is `devise/saml_sessions#create`. If you need to use a different path, you'll have to create the route to the same place, e.g. `post '/saml/consume' => "devise/saml_sessions#create", as: :user_session`.

Note that devise doesn't make this easy. Here's a config that might work:

`config/routes.rb`:

```
Rails.application.routes.draw do
  devise_for :users, skip: :all
  post '/saml/consume' => "devise/saml_sessions#create", as: :user_session
  devise_scope :user do
    scope "users", controller: 'devise/saml_sessions' do
      get :new, path: "saml/sign_in", as: :new_user_session
      get :destroy, path: "sign_out", as: :destroy_user_session
      get :metadata, path: "saml/metadata", as: :metadata_user_session
      match :idp_sign_out, path: "saml/idp_sign_out", via: [:get, :post]
    end
  end
end
```

Then the routes become:

```
         user_session POST     /saml/consume(.:format)            devise/saml_sessions#create
     new_user_session GET      /users/saml/sign_in(.:format)      devise/saml_sessions#new
 destroy_user_session GET      /users/sign_out(.:format)          devise/saml_sessions#destroy
metadata_user_session GET      /users/saml/metadata(.:format)     devise/saml_sessions#metadata
         idp_sign_out GET|POST /users/saml/idp_sign_out(.:format) devise/saml_sessions#idp_sign_out
```

**Comment by aaani** [comment]
Really great answer @adamstegman, I appreciate that. 

When I set up those route configs I got a devise routing error for /saml/consume because it wasn't scoped. When I moved it in inside the devise_scope :user block it worked perfectly! Thanks a lot! :+1: :+1: 

Feel free to close this issue.

**Comment by naveedtariq** [comment]
@adamstegman @apokalipto @aaani hey guys I am stuck in the same issue from long time, I would really appreciate if you please put me on some right track. I am doing it using Onelogin and my system is IDP based. So I make a post request from my Idp ( Onelogin ) to `saml/auth` it found the user but I am not sure why it is not authenticating the user.

My routes file

```ruby
  devise_scope :user do
    scope "users", controller: 'saml_sessions' do
      get :new, path: "saml/sign_in", as: :new_user_sso_session
      post :create, path: "saml/auth", as: :user_sso_session
      get :destroy, path: "sign_out", as: :destroy_user_sso_session
      get :metadata, path: "saml/metadata", as: :metadata_user_sso_session
      match :idp_sign_out, path: "saml/idp_sign_out", via: [:get, :post]
    end
  end
```

Configurations in devise.rb

```ruby

  config.saml_configure do |settings|
    settings.assertion_consumer_service_url     = "#{ENV['HOST']}users/saml/auth"
    settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    settings.name_identifier_format             = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
    settings.issuer                             = "https://myapp.onelogin.com/saml/metadata/551135"
    settings.authn_context                      = ""
    # settings.idp_entity_id                      = "https://app.onelogin.com/saml/metadata/551135"
    settings.idp_slo_target_url                 = "https://myapp.onelogin.com/trust/saml2/http-redirect/slo/551135"
    settings.idp_sso_target_url                 = "https://myapp.onelogin.com/trust/saml2/http-post/sso/551135"
    settings.idp_cert                           = <<-CERT.chomp
-----BEGIN CERTIFICATE-----
QrKVf+4l0h7kUsWKPWNWU4FlSLeWffdVA0EFe1nPiK8QhLBMevJGcSG7xg8MqiVb
oVOBNGDqWe/q5TVJJsONr1Sok1ASdUgfs6TpNTD9/+kza/qPwcb9IzBNI/052QeY
Pg==
-----END CERTIFICATE-----

    CERT
  end
```

Attribute-map.yml

```ruby
"urn:mace:dir:attribute-def:uid": "user_name"
"urn:mace:dir:attribute-def:email": "email"
"urn:mace:dir:attribute-def:name": "last_name"
"urn:mace:dir:attribute-def:givenName": "first_name"
```

I have seen in XML I am getting the email with which I guess it is finding the user but not sure why user is not getting authenticated. It would be great if you guys please share some knowledge. 

Thanks

**Comment by adamstegman** [comment]
@naveedtariq A few things I notice:

* that looks like a truncated certificate, did you just redact it for Github?
* your issuer URL is incorrect—it should be your app's metadata endpoint: `https://example.com/users/saml/metadata`
* why is your entity ID commented out?

**Comment by naveedtariq** [comment]
@adamstegman thanks for your response

 - yes I truncated the certificate deliberately because of security reasons.
 - Yes I have figured that out, the issuer URL is incorrect, but I have to point it to the audience URL in the Onelogin otherwise it make the response invalid.
 - Readded the entity ID.

**Comment by adamstegman** [comment]
> Yes I have figured that out, the issuer URL is incorrect, but I have to point it to the audience URL in the Onelogin otherwise it make the response invalid.

Correct! So you should have your app's metadata endpoint configured in OneLogin as the audience URL.

**Comment by cagedartist** [comment]
@adamstegman @apokalipto @aaani For the past year, our app has been working with 1.0 of devise_saml_authenticatable. Just tried to update and ran into something that also results in 401 Unauthorized. We're also using Onelogin. I'm using SSO Tracer to look at the SAML assertion and everything looks fine. The assertion from Onelogin has not changed. Our devise saml configuration has not changed. (It's similar to the @naveedtariq config.) Authentication fails and it's hard to figure out why. Did something change in ruby-saml, maybe? I tried changing saml_use_subject to true - in case our attribute-map wasn't working correctly - but that didn't change the outcome. Any thoughts?

**Comment by adamstegman** [comment]
@cagedartist a common issue is not having a Recipient configured. I observed that in Heroku's SSO setup, and we ran into that in our own OneLogin setup when we upgraded ruby-saml. 

#56 added some logging to help debug these situations, but @apokalipto hasn't released a new version yet. You could try running off master and looking for those logs.

**Comment by cagedartist** [comment]
Thanks @adamstegman - in the SAML response/assertion, I see Recipient="{recipient}" -- so your diagnosis may be correct.

**Comment by cagedartist** [comment]
Thanks for helping, @adamstegman - Recipient is filled in, now. Unfortunately, we still have the same problem. Do you know what Recipient is compared to? We've tried the app's base url (https://www.myapp.com) and we've tried the ACS url (https://www.myapp.com/users/saml/auth).

**Comment by adamstegman** [comment]
I actually thought it was the ACS URL. 

Looking through the [ruby-saml codebase](https://github.com/onelogin/ruby-saml) I don't actually see a reference to it besides in the schema. It does reference there that it's a URI; but since you're still seeing failures I guess that's not the issue.

Can you try running on master and seeing what's reported in the logs?

**Comment by naveedtariq** [comment]
this project never took me back :( why am i getting responses here?

Naveed Tariq

**Comment by adamstegman** [comment]
Sorry @naveedtariq. @cagedartist, could you create a new issue for more discussion about this?
