### ISSUE TITLE
password can't be blank

### ISSUE THREAD

**Issue by chetanbissa27** [apokalipto/devise_saml_authenticatable#41]
Hi All,

I have application where I am using devise and now want to integrate devise saml.I create IDP with ruby-saml-idp gem.I ran IDP on localhost:3001 and ran my SP application on 3000.Its redirecting to localhost:3001 login page I enter correct email and password and redirect back to 3000 but its throwing  password can't be blank.
my devise setting

config.saml_create_user = true
    config.saml_default_user_key = :email
    config.saml_session_index_key = :session_index
    config.saml_use_subject = true
    config.saml_configure do |settings|
        settings.assertion_consumer_service_url     = "http://localhost:3000/users/saml/auth"
        settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        settings.name_identifier_format             = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        settings.issuer                             = "http://localhost:3000/saml/metadata"
        settings.authn_context                      = ""
        settings.idp_sso_target_url                 = "http://localhost:3001/saml/auth"
        settings.idp_cert               = <<-CERT.chomp
-----BEGIN CERTIFICATE-----
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111_______IDP_CERTIFICATE________111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111
111111111111111111
-----END CERTIFICATE-----
      CERT
    end

**Comment by adamstegman** [comment]
Could you include some information about the error it's throwing? A stack trace would be ideal.

**Comment by chetanbissa27** [comment]
nested asn1 error

ruby-saml (1.1.2) lib/onelogin/ruby-saml/settings.rb:122:in `initialize'
ruby-saml (1.1.2) lib/onelogin/ruby-saml/settings.rb:122:in `new'
ruby-saml (1.1.2) lib/onelogin/ruby-saml/settings.rb:122:in `get_idp_cert'
ruby-saml (1.1.2) lib/onelogin/ruby-saml/response.rb:631:in `validate_signature'
ruby-saml (1.1.2) lib/onelogin/ruby-saml/response.rb:315:in `validate'
ruby-saml (1.1.2) lib/onelogin/ruby-saml/response.rb:79:in `is_valid?'
devise_saml_authenticatable (1.2.2) lib/devise_saml_authenticatable/strategy.rb:19:in `authenticate!'
warden (1.2.3) lib/warden/strategies/base.rb:53:in `_run!'
warden (1.2.3) lib/warden/proxy.rb:354:in `block in _run_strategies_for'
warden (1.2.3) lib/warden/proxy.rb:349:in `each'
warden (1.2.3) lib/warden/proxy.rb:349:in `_run_strategies_for'
warden (1.2.3) lib/warden/proxy.rb:319:in `_perform_authentication'
warden (1.2.3) lib/warden/proxy.rb:127:in `authenticate!'
devise (3.4.1) app/controllers/devise/sessions_controller.rb:16:in `create'
actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.13) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.13) lib/active_support/callbacks.rb:447:in `_run__4264673221546273783__process_action__654816836787618514__callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'

**Comment by chetanbissa27** [comment]
Please let me know the step I should follow.I am trying from last 7 days.I am not getting where I am wrong.

**Comment by adamstegman** [comment]
The [README of the ruby-saml-idp project](https://github.com/lawrencepit/ruby-saml-idp/blob/master/README.md) indicates that the fingerprint is actually `9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D`. Does using that setting help?

You can also access it at `SamlIdp::Default::FINGERPRINT`.

**Comment by chetanbissa27** [comment]
Ok thanks thats working now.What if I have third party IDP then what idp_cert_fingerprint I can use.
one more question do we have to configure all of three thing or one of them
1) idp_cert_fingerprint
2) SECRET_KEY 
3) X509_CERTIFICATE 

and if I am using third party IDP then how I can come to know about correct fingerprint or secretkey.

Thats a lot of question but it will help me.

Thanks

**Comment by apokalipto** [comment]
1) You have to calculate the fingerprint. You may use OpenSSL for that
`openssl x509 -in /path/to/certificate.crt -noout -fingerprint`

**Comment by adamstegman** [comment]
You can use either the fingerprint *or* the key; you don't need both.

**Comment by adamstegman** [comment]
It's been a couple weeks so I'll go ahead and close this issue. Let us know if you're still stuck.
