### ISSUE TITLE
IDP Certificate Question

### ISSUE THREAD

**Issue by rsl** [apokalipto/devise_saml_authenticatable#42]
i took the IDP Certificate value from the provider's metadata file. it doesn't seem to be formatted like the example in the README [or in my own ca-certificates.crt file]. it's a single [long] line. doesn't have the BEGIN/END lines either. am i grabbing the wrong thing or is it just formatted incorrectly? if the latter [god i hope], can i just truncate line lengths and add the BEGIN/END lines?

not sure where else to ask about this so apologies if this isn't it.

**Comment by adamstegman** [comment]
Does `openssl` read it correctly? I'm not sure what format it might be in, but for instance a PEM-encoded certificate can be read like so: `openssl x509 -in ./cert.pem -noout -text`

**Comment by rsl** [comment]
thanks for that info. yeah. that works.

now being told that the metadata file we're supposed to be generating [as a consumer] is missing data nodes [that i've seen in the provider's metadata and aren't in the example one you show]. does 
![2](https://cloud.githubusercontent.com/assets/92/14608626/80d52642-0554-11e6-8aea-711cc9b2798d.png) look like something we should be generating? right now, it sounds like i'm going to have to dump the plugin because they're insisting our metadata file should look more like theirs.

**Comment by adamstegman** [comment]
You're looking in the right place since [ruby-saml generates the metadata file](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/metadata.rb). If it can't generate fields that your IdP requires a pull request to ruby-saml may be in order to add the capability.

**Comment by rsl** [comment]
good news... i've been able to generate one with the test cert/key from ruby-saml's test suite but unfortunately can't find where to get them for our server. host is telling me to use rsa key pair from ssh-keygen but that seems wrong. i'm in the perfect telephone game between our end client [IDP], managed hosting, plugin code, and never having done any of this before nor being a sysadmin. hah.

**Comment by adamstegman** [comment]
That sounds correct—you should create a keypair for your SP and give them your public key so they can verify it.

**Comment by rsl** [comment]
hah. awesome. they gave me a different way to generate as well [via openssl instead of ssh-keygen] which gave me a cert and private_key pair that passes muster. thanks so much for the help. 

don't ask me why my generating a keypair seemed so wrong to me. lol
