### ISSUE TITLE
Route clash with database_authenticatable

### ISSUE THREAD

**Issue by thomasgallagher** [apokalipto/devise_saml_authenticatable#43]
user.rb has:
devise :invitable, :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable, :saml_authenticatable

When running rake routes:
ArgumentError: Invalid route name, already in use: 'new_user_session' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created

Removing database_authenticatable fixes the problem - would namespacing the routes fix this? Happy to submit a PR if you agree.

**Comment by adamstegman** [comment]
#25 goes over how to make the two strategies coexist. Also make note of #22 when using this with database authentication.

How would you apply namespacing in a PR? I don't think we always want namespacing, only when there's more than one strategy that requires routing.

**Comment by thomasgallagher** [comment]
Thank you for the quick reply and the references.

My thinking was along the lines of:

`
ActionDispatch::Routing::Mapper.class_eval do
  protected
  def devise_saml_authenticatable(mapping, controllers)
    resource :saml_session, :only => [], :controller => controllers[:saml_sessions], :path => "" do
      get :new, :path => "saml/sign_in", :as => "new"
      post :create, :path=>"saml/auth"
      match :destroy, :path => mapping.path_names[:sign_out], :as => "destroy", :via => mapping.sign_out_via
      get :metadata, :path=>"saml/metadata"
      match :idp_sign_out, :path=>"saml/idp_sign_out", via: [:get, :post]
    end
  end
end
`

So a new SAML session would become "new_user_saml_session_path" and normal routes would retain the database authentication paths. It may need to be a setting as I imagine some people will want to replace the default devise routes.

Maybe I'm showing my naivety of the inner workings of devise but just a thought?

**Comment by adamstegman** [comment]
That's a really interesting idea. I didn't really think that so many people would use multiple strategies, but based on how many times this has come up, your idea does seem good.

It would work for everything except logging out. The application developer still needs to know which controller to use for the logout link. Maybe we need to incorporate both your idea and something like the controller action I put near the bottom of #25.

**Comment by thomasgallagher** [comment]
If we ask the developer to favour the SAML controller to sign out (so the gem has control of what happens) then perhaps the devise resource could be inspected for database_authenticatable and any  sign out logic specific to it could be called?

**Comment by adamstegman** [comment]
Building in something specific to *database* authentication is a dangerous road that I'd like to avoid if possible. Supporting arbitrary other strategies is the goal I think. Fortunately just calling `sign_out` should work for most strategies.

Enforcing that the SAML controller handles sign out is probably appropriate, and we can address any issues with that later on.

The SAML controller actually just defers to devise, which should be the right thing to do in basically every case. The only thing that's important about it for signing out is [`#after_sign_out_path`](https://github.com/apokalipto/devise_saml_authenticatable/blob/64874d478a595c355816af15e4d32afaa45fd1d6/app/controllers/devise/saml_sessions_controller.rb#L42), which sends the user back to the IdP.

**Comment by rsl** [comment]
the current implementation clashes in the model as well because it overrides update_with_password assuming no one is using a database_authenticable strategy as well. :/

**Comment by adamstegman** [comment]
Given there's a workaround for this, I'm going to close it. Please let me know if you have any more questions or issues.

**Comment by gotoAndBliss** [comment]
@thomasgallagher Would you mind sharing your final solution? I have multiple strategies going on.. and can't seem to find a way to play `devise_saml_authenticatable` in the mix.

**Comment by thomasgallagher** [comment]
I actually ended up using https://github.com/onelogin/ruby-saml with devise's sign_in method once authed.
