### ISSUE TITLE
`update_with_password` clashes with Devise's DatabaseAuthenticatable `update_with_password`

### ISSUE THREAD

**Issue by mathildemouw** [apokalipto/devise_saml_authenticatable#45]
My team wants to use the devise_saml_authenticatable gem to add SAML log in to our app for certain groups of users, while maintaining regular devise login for the other users. So far this gem has been perfect for our use case with one exception. Adding SAML login broke devise's `update_with_password`, so users would no longer be able to update attributes that require a password to be entered. The `Devise::Models::SamlAuthenticatable#update_with_password` overwrites the `Devise::Models::DatabaseAuthenticatable#update_with_password` coming from devise, because of the way devise loads the models.

We would like to submit a pull request to modify the gem to support our use case, but want to make sure that our changes will fit with the intended behavior of the gem. Is there other functionality in devise_saml_authenticable that will break if we remove `Devise::Models::SamlAuthenticatable#update_with_password`? We'd love to help work on this gem to make it work for us, and hopefully this would help others as well!

**Comment by adamstegman** [comment]
I'm not sure why `#update_with_password` is in there—maybe @apokalipto can provide some context. 

Removing it seems fine to me! Thanks in advance for the contribution.

**Comment by apokalipto** [comment]
Hi guys, 

First of all, thank you very much for your work. 

You are right. I see no reason why update_with_password should be there. Remove it and lets see what happens. Cheers!

**Comment by mathildemouw** [comment]
@apokalipto @adamstegman Thanks for your responses! In that case, we will go ahead and open the PR that removes `SamlAuthenticatable#update_with_password` asap.

**Comment by adamstegman** [comment]
@mathildemouw @blakeshall I'm going to close this since your PR is merged, but please let me know if this needs any more discussion.
