### ISSUE TITLE
case insensitive keys - authenticate_with_saml method

### ISSUE THREAD

**Issue by alanruth** [apokalipto/devise_saml_authenticatable#48]
in model.rb line 45, we work to get the key that will be used to authenticate.

if 
```
Devise.saml_use_subject
```
 is true, we go after the NameID attribute and get the value. 

however when 
```
Devise.saml_use_subject
``` 
is false, we use the attribute map (if present) and then go find the attribute to get the value. In this block we attempt to downcase the attribute value if Devise.case_insensitive_keys.include?(key) is true. 

shouldn't we also be attempting to downcase the NameID attribute when Devise.saml_use_subject is true and Devise.case_insensitive_keys.include?(key) is true?

The reason i mention this is that my client uses upper case letters in their email addresses and this mixed case email is being sent in via the response. However because we don't downcase this line
```
resource = where(key => auth_value).first
```
always returns false.

or is the SAML standard to always downcase when using subject?

**Comment by adamstegman** [comment]
Seems legit to use the Devise setting in both places. Would you be willing to make a PR?

**Comment by alanruth** [comment]
Sure. Will do.
