### ISSUE TITLE
ActionDispatch::Request::Session not set after successful authentication

### ISSUE THREAD

**Issue by danielbonnell** [apokalipto/devise_saml_authenticatable#62]
I'm trying to implement a SAML strategy for Devise in my app in order to achieve SSO. I've never done anything with SSO or SAML before, so I feel like I barely understand most of this. I managed to configure a test IDP app on OneLogin and successfully authenticate as a user of my app. Unfortunately once I've authenticated, the user session isn't properly set and I'm forced to try to log in again, thereby creating an infinite loop. I'm using Devise 3.5.2.

As you can see from my code below, I've inserted a `binding.pry` in `SessionsController#create`. When I authenticate via SSO and inspect the `session` hash, I see the following:

    [1] pry(#<SamlSessionsController>)> session
    => {"warden.user.contact.key"=>[[868], "$2a$10$mPPKs3tUQJYPaHJa4nRoX."]}

When I authenticate by signing in with my email and password, I see the following instead:

    [1] pry(#<SessionsController>)> session
    => #<ActionDispatch::Request::Session:0x007ff3f8438778 ...>
    [2] pry(#<SessionsController>)> session.as_json
    => {"session_id"=>"10d6eaed4573c6a7e1cf234733ed62f6", "warden.user.contact.key"=>[[868], "$2a$10$mPPKs3tUQJYPaHJa4nRoX."]}

I'm not sure exactly what's happening, but clearly something is different with the `session` object. I suspect this is my problem, however I've been unable to find any resources on how to fix this. I've tried using `warden.set_user(resource, scope: :contact)`, but that made no difference. I've also tried setting the `session_id` manually using two different approaches:

    # This does work when signed in via SSO. I get a NoMethodError: undefined method generate_sid for nil::NilClass
    session.options[:id] = session.instance_variable_get(:@by).generate_sid

    # This approach works for setting a session_id, but the session is reset as soon as I exit from pry.
    session['session_id'] = SecureRandom.hex(16)

    # I've also tried turning off renew, but to no avail
    session.options[:renew] = false

Here is my `config/initializers/devise.rb` (comments remove for brevity):

    require 'id_p_settings_adapter'
    Devise.setup do |config|
        config.secret_key = '....'

        require 'devise/orm/active_record'

        config.case_insensitive_keys = [ :email ]
        config.strip_whitespace_keys = [ :email ]
        config.skip_session_storage = [:http_auth]
        # Note that I also tried adding :saml_auth here as well. Made no difference
        config.skip_session_storage = [:http_auth, :saml_auth]

        config.stretches = Rails.env.test? ? 1 : 10
        config.reconfirmable = true
        config.password_length = 8..128
        config.reset_password_within = 6.hours
        config.sign_out_via = :delete

        config.warden do |manager|
            manager.failure_app = MyAuthFailure
        end

        config.saml_create_user = false
        config.saml_update_user = true
        config.saml_default_user_key = :email
        config.saml_session_index_key = :session_index
        config.saml_use_subject = true
        config.idp_settings_adapter = IdPSettingsAdapter
        config.idp_entity_id_reader = DeviseSamlAuthenticatable::DefaultIdpEntityIdReader
    end

I have the following in `config/routes.rb`:

    devise_for :contacts, skip: :saml_authenticatable, controllers: {
        registrations: "registrations",
        sessions: "sessions",
        passwords: "passwords"
    }

    devise_scope :contact do
        get '/sign_in' => 'sessions#new'
        get '/sign_out' => 'sessions#destroy'
        get '/welcome' => 'confirmations#show'
        patch '/welcome' => 'confirmations#after_confirmation'
        get '/recover' => 'passwords#new'
        get '/reset' => 'passwords#edit'
        get '/account' => 'registrations#edit'
        patch '/account' => 'registrations#update'
        get '/preferences/:token' => 'registrations#preferences'
        patch '/preferences/:token' => 'registrations#update_preferences'

        # SSO Routes
        get 'saml/sign_in' => 'saml_sessions#new', as: :new_user_sso_session
        post 'saml/auth' => 'saml_sessions#create', as: :user_sso_session
        get 'saml/sign_out' => 'saml_sessions#destroy', as: :destroy_user_sso_session
        get 'saml/metadata' => 'saml_sessions#metadata', as: :metadata_user_sso_session
        match 'saml/idp_sign_out' => 'saml_sessions#idp_sign_out', via: [:get, :post]
    end

Here is my IdPSettingsAdapter in `lib/id_p_settings_adapter.rb`:

    class IdPSettingsAdapter
        def self.settings(idp_entity_id)
            company = Company.find_by(idp_entity_id: idp_entity_id)

            if company.present?
                {
                    assertion_consumer_service_url: company.assertion_consumer_service_url,
                    assertion_consumer_service_binding: company.assertion_consumer_service_binding,
                    name_identifier_format: company.name_identifier_format,
                    issuer: company.issuer,
                    idp_entity_id: company.idp_entity_id,
                    authn_context: company.authn_context,
                    idp_slo_target_url: company.idp_slo_target_url,
                    idp_sso_target_url: company.idp_sso_target_url,
                    idp_cert_fingerprint: company.idp_cert_fingerprint
                }
            else
                {}
            end
        end
    end

I have the following in `app/controllers/saml_sessions_controller.rb`:

    require "ruby-saml"

    class SamlSessionsController < SessionsController
        include DeviseSamlAuthenticatable::SamlConfig
        skip_before_filter :verify_authenticity_token, raise: false
        protect_from_forgery with: :null_session

        def new
            idp_entity_id = Company.friendly.find(@_request.env['HTTP_HOST'].split('.')[0]).idp_entity_id
            request = OneLogin::RubySaml::Authrequest.new
            action = request.create(saml_config(idp_entity_id))
            redirect_to action
        end

        def metadata
            idp_entity_id = Company.friendly.find(@_request.env['HTTP_HOST'].split('.')[0]).idp_entity_id
            meta = OneLogin::RubySaml::Metadata.new
            render :xml => meta.generate(saml_config(idp_entity_id))
        end

        def create
            @idp_entity_id = Company.friendly.find(@_request.env['HTTP_HOST'].split('.')[0]).idp_entity_id
            response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], settings: saml_config(@idp_entity_id))

            if !response.is_valid?
                puts "SAML FAILED WITH ERROR: "
                puts response.errors
            end
            super
        end

        def idp_sign_out
            idp_entity_id = Company.friendly.find(@_request.env['HTTP_HOST'].split('.')[0]).idp_entity_id

            if params[:SAMLRequest] && Devise.saml_session_index_key
                saml_config = saml_config(company)
                logout_request = OneLogin::RubySaml::SloLogoutrequest.new(params[:SAMLRequest], settings: saml_config(idp_entity_id))
                resource_class.reset_session_key_for(logout_request.name_id)

                redirect_to generate_idp_logout_response(saml_config(idp_entity_id), logout_request.id)
            elsif params[:SAMLResponse]
                #Currently Devise handles the session invalidation when the request is made.
                #To support a true SP initiated logout response, the request ID would have to be tracked and session invalidated
                #based on that.
                if Devise.saml_sign_out_success_url
                    redirect_to Devise.saml_sign_out_success_url
                else
                    redirect_to action: :new
                end
            else
                head :invalid_request
            end
        end

        protected

        # Override devise to send user to IdP logout for SLO
        def after_sign_out_path_for(_)
            request = OneLogin::RubySaml::Logoutrequest.new
            request.create(saml_config)
        end

        def generate_idp_logout_response(saml_config, logout_request_id)
            OneLogin::RubySaml::SloLogoutresponse.new.create(saml_config, logout_request_id, nil)
        end
    end

And here is `app/controllers/sessions_controller.rb`:

    class SessionsController < Devise::SessionsController
        layout 'layouts/application'
        before_action :authorize_viewer, except: [:new, :create]

        def create
            self.resource = warden.authenticate(auth_options)

            if self.resource.present?
                set_flash_message(:notice, :signed_in) if is_flashing_format?
                sign_in(resource_name, resource, bypass: true)
                yield resource if block_given?

                binding.pry
                if @idp_entity_id && warden.authenticated?(:contact)
                    session.options[:id] = session.instance_variable_get(:@by).generate_sid
                    session['session_id'] = SecureRandom.hex(16)
                    session.options[:renew] = false
                end

                redirect_to '/home'
            else
                flash[:error] = I18n.t "devise.failure.invalid"
                redirect_to '/sign_in'
            end
        end
    end

And here is `app/models/contact.rb`. Note that I added a `session_index` column to the `Contact` model.

    class Contact < ActiveRecord::Base
        devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable,
            :confirmable, :saml_authenticatable

        belongs_to :company
        validates_presence_of :email, :first_name, :last_name
        validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
        validates_uniqueness_of :email, scope: :company_id
    end

**Comment by adamstegman** [comment]
It's definitely strange that you see `session` as just a Hash. Does `session.class.name` show `Hash`?

Could `protect_from_forgery with: :null_session` be a factor here? I noticed it in your `SamlSessionsController`, immediately after *skipping* that same protection (adding it after skipping probably negates the skip by re-adding the filter).

**Comment by danielbonnell** [comment]
Yeah, `session.class.name == Hash`. I actually came to the same realization. I changed it to `protect_from_forgery with: :null_session, except: :create` and now it seems to work as expected. Seems kind of obvious in retrospective. 

Disabling CSRF for `saml_sessions#create` feels a bit risky. It seems like the root problem here is that no CSRF token is present (I noticed an error about this in the logs), which was causing my issue in the first place. Is there a better way to solve this than just disabling CSRF protection on `create`?

**Comment by adamstegman** [comment]
> Is there a better way to solve this than just disabling CSRF protection on `create`?

Definitely! [ruby-saml](https://github.com/onelogin/ruby-saml) validates the response you get from the IdP, including that it has a valid Signature using the IdP certificate you configured. You could also ensure it matches the request ID you sent, but this gem currently doesn't do that.

I don't think you could make CSRF protection work at all on an endpoint like this, where requests come from another system. The tokens are generated by Rails in the form helpers.

**Comment by danielbonnell** [comment]
Good point. CSRF doesn't really add much protection in this case. I'll mark this as closed since it's working now. Thanks!
