### ISSUE TITLE
Ruby Saml Issuers Method Removed

### ISSUE THREAD

**Issue by newdark** [apokalipto/devise_saml_authenticatable#67]
https://github.com/onelogin/ruby-saml/commit/9b8e8e2fb1f438a482a25b96132e41c1e533c1f2#diff-00524fdf114f961e4ff1ff4a04fd8490L226

ruby-saml (1.4.0) removed method issuers which looks like it was dependent on this line of code here 

https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable/default_idp_entity_id_reader.rb#L7

![screen shot 2016-10-17 at 2 45 13 pm](https://cloud.githubusercontent.com/assets/13140/19452870/4fc278ee-9478-11e6-933f-efe0ba3f0658.png)

The temp solution for me was to use ruby-saml (1.3.1). That version of the gem still has the method. However going forward the method is no longer present.

**Comment by adamstegman** [comment]
Thank you for reporting this! I logged onelogin/ruby-saml#359 to ask what their recommendation is.

I'll also see if I can add regular Travis builds and build against multiple versions of ruby-saml since they've broken their API in a minor release.

**Comment by adamstegman** [comment]
Looks like this is fixed in 1.4.1, and builds are succeeding again.
