### ISSUE TITLE
Support 0.8.1 version

### ISSUE THREAD

**Issue by mikelitton** [apokalipto/devise_saml_authenticatable#7]
The following pull request needs to be merged in order to support the latest version of RubySAML.

https://github.com/apokalipto/devise_saml_authenticatable/pull/5

All three open pull requests seems to be related to the same problem.

**Comment by adamstegman** [comment]
Thanks for the pointer! We'll address this via those pull requests. I'll go ahead and close this issue in favor of the open PRs.
