### ISSUE TITLE
Make SLO optional?

### ISSUE THREAD

**Issue by cagedartist** [apokalipto/devise_saml_authenticatable#71]
In our case (medium-size college with dozens of SAML apps) we are unable to provide a consistent single logout experience. (In addition, our staff is divided about whether SLO is the optimal user experience, even if it could be made to work.) Instead, all apps log out individually and redirect to the IdP's logout method, which logs out of the IdP and redirects to a central page that explains what just happened. 

Perhaps SLO could be optional?

**Comment by adamstegman** [comment]
What exactly do you have in mind to make it optional? Return a 400 or something to an IdP-initiated logout request? That seems like it might be useful in cases where your IdP does not allow you to disable it for individual applications, I'm just uncertain how common that is.

**Comment by adamstegman** [comment]
I'm going to close this since it hasn't had any discussion in quite some time. Please reply if you have any more questions.
