### ISSUE TITLE
OneLogin::RubySaml::ValidationError

### ISSUE THREAD

**Issue by prosanelli** [apokalipto/devise_saml_authenticatable#73]
I am upgrading my application from Rails 4.2.7.1 to Rails 5.0.0.1 so I had to upgrade the devise_saml_authenticatable gem from 1.2.2 => 1.3.0. I am getting the following error when I try to login with our saml provider:

```
Started GET "/admins/saml/sign_in" for 127.0.0.1 at 2016-11-14 14:45:11 -0500
Processing by Admin::SamlSessionsController#new as HTML
Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='XXXX' Destination='XXX' ID='XXXX' IssueInstant='2016-11-14T19:45:11Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>https://XXXX/saml/metadata</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/></samlp:AuthnRequest>
Redirected to https://XXXX/sso/saml?SAMLRequest=XXXX
Completed 302 Found in 3ms (Flexirest: 0.0ms for 0 calls | ActiveRecord: 0.0ms)

Started POST "/admins/saml/auth" for 127.0.0.1 at 2016-11-14 14:45:12 -0500
Incoming Headers:
  Origin: XXX
  Access-Control-Request-Method: 
  Access-Control-Request-Headers: 
Processing by Admin::SamlSessionsController#create as HTML
Parameters: {"SAMLResponse"=>"PD94bWwgdmVy.....", "RelayState"=>""}
Completed 500 Internal Server Error in 18ms (Flexirest: 0.0ms for 0 calls | ActiveRecord: 0.0ms)

OneLogin::RubySaml::ValidationError - An EncryptedAssertion found and no SP private key found on the settings to decrypt it. Be sure you provided the :settings parameter at the initialize method:
  ruby-saml (1.3.1) lib/onelogin/ruby-saml/response.rb:750:in `generate_decrypted_document'
  ruby-saml (1.3.1) lib/onelogin/ruby-saml/response.rb:57:in `initialize'
  devise_saml_authenticatable (1.3.0) lib/devise_saml_authenticatable/strategy.rb:9:in `valid?'
  warden (1.2.6) lib/warden/proxy.rb:355:in `block in _run_strategies_for'
  warden (1.2.6) lib/warden/proxy.rb:353:in `_run_strategies_for'
  warden (1.2.6) lib/warden/proxy.rb:323:in `_perform_authentication'
  warden (1.2.6) lib/warden/proxy.rb:127:in `authenticate!'
  devise (4.2.0) app/controllers/devise/sessions_controller.rb:17:in `create'
  app/controllers/admin/saml_sessions_controller.rb:9:in `create'
```

**Comment by kevinmtrowbridge** [comment]
This error came up for me as well.  It came up in the context of attempting to validate encrypted SAML responses.  I was able to get it working with the above commits.  I am not at all sure that my changes are correct, in fact I imagine that the way I pass in `settings: Devise.saml_config` using that "singleton" style method, would break the 1.3.0 feature to support multiple IdPs.

**Comment by adamstegman** [comment]
@kevinmtrowbridge It looks like including `SamlConfig` in the `DefaultIdpEntityIdReader` would allow you to use `saml_config` there.

**Comment by prosanelli** [comment]
@kevinmtrowbridge thanks - your solution works. would it be possible to merge this code into the gem?

**Comment by jproctor** [comment]
The patch above works for multiple IdPs, also, but only because I can still define the SP’s cert and private key in `devise.rb`:

```ruby
config.idp_settings_adapter = MyAdapter
config.saml_configure do |settings|
  # You can include here anything common to all your IdPs
  settings.assertion_consumer_service_url = "#{my_base_url}/users/saml/auth"
  settings.issuer                         = "#{my_base_url}/saml/metadata"
  # ...
  settings.certificate                    = my_sp_certificate
  settings.private_key                    = my_sp_private_key
end
```

This works because `SamlConfig` _amends_ `Devise.saml_config` when there’s an adapter, rather than requiring all the settings for every IdP.

If my SP had different certs for different IdPs, there would still be the problem of identifying which IdP the encrypted response came from, since `idp_entity_id` isn’t necessarily available. Possibly some session/cookie magic would suffice.

**Comment by adamstegman** [comment]
Merged in #106 to address this. Thanks to @jproctor!

**Comment by jproctor** [comment]
And thanks again to @kevinmtrowbridge for the actual fix!

**Comment by kevinmtrowbridge** [comment]
Thank you! Sorry I was AWOL and didn't help with the integration of the fix. I just, stopped working in this area.
