### ISSUE TITLE
Case Insensitive Emails

### ISSUE THREAD

**Issue by danielbonnell** [apokalipto/devise_saml_authenticatable#75]
Hello,

I've observed a bug where if a user tried to authenticate with their email address and the case doesn't match what is in the system, the user is not found.

For example, in my IDP I have `Foo.Bar@example.com`. In my SP app I have `foo.bar@example.com`. When the SP receives an assertion from the IDP to sign in Foo Bar, it should match `Foo.Bar@example.com` to `foo.bar@example.com` because email addresses are case insensitive.

In `devise.rb` I've set `config.case_insensitive_keys = [:email]` but that seems to have no effect.

I'm running `v1.3.0` with Devise `3.5.2`.

Thanks!

**Comment by adamstegman** [comment]
As discussed in #76, this should have been addressed already by #68. I'm going to close this issue. Please reply if you have any more questions.
