### ISSUE TITLE
Integrating devise application with okta using devise_saml_authenticatable gem facing issue

### ISSUE THREAD

**Issue by saladidesai** [apokalipto/devise_saml_authenticatable#79]
Hi anybody can help me out,i am struck with integrating my application (service provider) into okta (idp) using devise_saml_authenticatable gem and i am running it is in local so i am facing some issue so this i have done in my application below mentioned....

in my rake routes
new_user_session GET /users/saml/sign_in(.:format) devise/saml_sessions#new
POST /users/saml/auth(.:format) devise/saml_sessions#create destroy_user_session DELETE /users/sign_out(.:format) devise/saml_sessions#destroy
metadata_user_session GET /users/saml/metadata(.:format) devise/saml_sessions#metadata
idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format) devise/saml_sessions#idp_sign_out

attribute-map.yml file (it is devise user table email and admin)

"urn:mace:dir:attribute-def:email": "email"
"urn:mace:dir:attribute-def:admin": true

In devise.rb file i have added

config.saml_create_user = true
   config.saml_update_user = true
   config.saml_default_user_key = :email
   config.saml_session_index_key = :session_index
   config.saml_use_subject = true
   config.idp_settings_adapter = nil

config.saml_configure do |settings|
settings.assertion_consumer_service_url = "http://localhost:3000/users/saml/auth"
settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
settings.issuer       = "http://localhost:3000"
settings.idp_sso_target_url = "https://dev-351954.oktapreview.com/app/template_saml_2_0/exk9cv60hhmStgUJ90h7/sso/saml "
settings.idp_cert_fingerprint = "XxxxxxxxxxxxxxxxxxxX"
settings.name_identifier_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

end

In my application_controller

protect_from_forgery
check_authorization :unless => :devise_controller?
before_filter :authenticate_user!
layout :layout_by_resource

so these are all in my application so i am facing these issue pasted below here
WARNING: Can't verify CSRF token authenticity
  User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`email` = 'supreet.aladidesai@example.com' LIMIT 1
Completed 401 Unauthorized in 145.0ms
Processing by Devise::SamlSessionsController#new as HTML

WARNING: Can't verify CSRF token authenticity
  CACHE (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`email` = 'supreet.aladidesai@example.com' LIMIT 1
Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='http://localhost:3000/users/saml/auth' Destination='https://dev-351954.oktapreview.com/app/template_saml_2_0/exk9cv60hhmStgUJ90h7/sso/saml ' ID='_462452ee-6cf5-4b76-a542-afa7a6474469' IssueInstant='2017-01-20T07:27:16Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://localhost:3000</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/><samlp:RequestedAuthnContext Comparison='exact'><saml:AuthnContextClassRef></saml:AuthnContextClassRef></samlp:RequestedAuthnContext></samlp:AuthnRequest>
Redirected to https://dev-351954.oktapreview.com/app/template_saml_2_0/exk9cv60hhmStgUJ90h7/sso/saml ?SAMLRequest=fVLLbtswEPwV3XiSSSl6wIRlQLARwEVaFHbTQy%2FGVlpHQkiR5VKO%2B%2FellDjwocmVO4%2Fd4awItLKyHn037PHPiOSjmgid782wMQONGt0B3blv8HH%2FULHOeys5V6YB1Rny8k4IwcfAID5pcQhSLNoGoX6ASeWVQ4HU4jm%2By5Nlni3Mswfr8Nzjy6IxmoO13KO2CjweJ51jehQcL8%2FL5lyIrtMH%2F%2FT4ZSm6khOZ2Sli0W5bsWNWpFmeIsZFc8rj7HdZxJBnaQwnKKHIyiwrlgFKNOJuIA%2BDr1gqkjIWSZyKH6KUaSmT4heLfoYj5oXThWDRRauB5ORUsdEN0gD1JAfQSNI38lB%2FfZABKOEa1y3Ffs6xznjTGMXWqwkt5%2B3c%2Br%2FhrvgtZPX6Yd%2BC5G773ai%2B%2BRvVSpmXjcOQXcW8G5FF98Zp8B8vkSyS%2BaVv49MMlaihV3XbOiRi%2FOrz1gls54aEQni8%2BGhjtAXX05QVXqDx1ztuURsVktnjaf12wCezD3zep7f1XP8D
Completed 302 Found in 79.2ms (ActiveRecord: 0.0ms)

**Comment by adamstegman** [comment]
Are you using the latest version of this gem? There should be log messages indicating why you got a 401—either resource could not be found or an invalid SAML response.

**Comment by perryism** [comment]
@saladidesai did you try `1.3.0`? We are also having issue with `1.3.1`

**Comment by taylor01** [comment]
works fine for me.  what version of the gem are you using?
