### ISSUE TITLE
Where is the correct place to implement saml_failed_callback?

### ISSUE THREAD

**Issue by pabloq** [apokalipto/devise_saml_authenticatable#82]
Hi,

I'm trying to add a custom failure page but I don't know where this class must be defined and how. For me, this correspond to the controller layer but it looks like this just calls a constructor for a user defined class. How can I implement a redirect to a specific to controller action to manage the failure?

Thanks!

**Comment by apokalipto** [comment]
Hi,

You should just write a Class that implements a `handle(response, strategy)` method that is called when the strategy fails. You could place the class in your lib directory and reference it in the devise initializer.
```ruby
#lib/my_saml_failure.rb

class MySamlFailure
 def handle(response,strategy)
  #your special handling code here
  end
end
```
```ruby
#config/initializers/devise.rb
Devise.setup do |config|
  config.saml_failed_callback = MySamlFailure
# ... all your other config
end
```
This is where the saml failure gets instantiated and the method called
https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable/strategy.rb#L46

Pura Vida!

**Comment by pabloq** [comment]
great thanks!

**Comment by BigAlUK** [comment]
Hi,  I'm probably being stupid, but do you have an example of redirecting out of this failure class?

**Comment by apokalipto** [comment]
I don't, but you can do something like this

```ruby
class MySamFailure < ApplicationController
  def handle(response,strategy)
    redirect_to root_path, alert: "Your customized eror message!"
  end
end

**Comment by taggartbg** [comment]
@apokalipto I have tried the block above + a few similar methods.  I don't seem to have an implicit `request` object to attach a flash message to since this isn't being called as part of a request:
```
ActionController::Base#flash delegated to request.flash, but request is nil
```
and `strategy.redirect!` doesn't seem to support handling a flash message either.

Any thoughts?

**Comment by kevine-voicera** [comment]
Any solution here?

**Comment by vinhboy** [comment]
If you want to do a redirect on failure, you have to follow the Devise instructions here:

https://github.com/heartcombo/devise/wiki/How-To:-Redirect-to-a-specific-page-when-the-user-can-not-be-authenticated

For me personally, since I only want to redirect on failed SAML auth, I implemented the `CustomFailure#respond` like this:

```
  def respond
    if warden_options[:attempted_path] == "/users/saml/auth"
      redirect_to 'mypath'
    else
      super
    end
  end
```
