### ISSUE TITLE
Unable to run migrations

### ISSUE THREAD

**Issue by vmvwebworks** [apokalipto/devise_saml_authenticatable#83]
Hello, i created this threat here
http://stackoverflow.com/questions/42395460/unable-to-run-migration-after-configure-devisesamlauthenticatable-rails-gem

**Comment by mitch-lindsay** [comment]
I could be wrong but this looks to be very similar to an existing issue.  https://github.com/apokalipto/devise_saml_authenticatable/issues/25  If you're going to run both saml_authenticatable and database_authenticatable then you need to do a little extra work to ensure that unique routes are available.

**Comment by vmvwebworks** [comment]
I suggest to update the gem guide when we find a solution for work together both, common user registration and SAML registration.

**Comment by adamstegman** [comment]
Thanks for the suggestion. I took my comments from #25 and put them in a wiki page: https://github.com/apokalipto/devise_saml_authenticatable/wiki/Supporting-multiple-authentication-strategies
