### ISSUE TITLE
Allow for clock drift

### ISSUE THREAD

**Issue by TLaborde** [apokalipto/devise_saml_authenticatable#90]
the ruby-saml lib allow for clock drift [current doc](https://github.com/onelogin/ruby-saml#clock-drift) but not this gem.

Could that be added ?

**Comment by adamstegman** [comment]
This seems legitimate, would you want to add a configuration option that defaults to `nil`?

**Comment by TLaborde** [comment]
So, i think a fork already applied it:
https://github.com/kevinmtrowbridge/devise_saml_authenticatable/commit/bc493e445a91d4f0d68f799ee75ac8295b0a613c

It put the setup in Devise saml configuration. Could that be backported? is it a good way of doing it?
