### ISSUE TITLE
Devise.saml_resource_locator returns NoMethodError

### ISSUE THREAD

**Issue by amrocco** [apokalipto/devise_saml_authenticatable#95]
NoMethodError: undefined method `saml_resource_locator' for Devise:Module

Judging by the mattr_accessor being set here I don't think this should be happening?
https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable.rb#L113

**Comment by adamstegman** [comment]
What version of the gem are you using? Can you provide the rest of the stack trace?

**Comment by amrocco** [comment]
Hi Adam,

Apologies for not providing that info from the beginning. The version I am using is 1.3.1
Here is the stack trace:

`irb(main):001:0> Devise.saml_resource_locator
NoMethodError: undefined method `saml_resource_locator' for Devise:Module
        from (irb):1
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /home/anthony/metameetings/modules/metameetings2/qa/bin/rails:11:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/command_wrapper.rb:38:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:191:in `block in serve'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
`

Or if I try to set Devise.saml_resource_locator in an initializer:

`/home/anthony/metameetings/modules/metameetings2/qa/config/initializers/devise.rb:318:in `<top (required)>': undefined method `saml_resource_locator=' for Devise:Module (NoMethodError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:413:in `call'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
        from /home/anthony/metameetings/modules/metameetings2/qa/config/environment.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
`

**Comment by adamstegman** [comment]
Try updating to 1.3.2—that attribute wasn't released in 1.3.1.

**Comment by amrocco** [comment]
That seems to have worked, thanks!

In my initializer I added:
```
 Devise.saml_resource_locator = Proc.new do |model, saml_response, auth_value|
     model.where(Devise.saml_default_user_key => auth_value).where.not(type: 'GeneralPublicUser').first
 end
```
Now when I Iogin through my IDP it looks like it gets caught in a redirect loop rather than redirecting back to my app. This happened to me previously when my Settings Adapter wasn't set up properly. Has anything changed with that in the new update?

**Comment by adamstegman** [comment]
I'm not sure how to resolve that infinite loop. The SAML strategy fails authentication for some reason ([which should be logged](https://github.com/apokalipto/devise_saml_authenticatable/blob/ce9822ea23d7e0f03757534fc75679d2cb1e3827/lib/devise_saml_authenticatable/strategy.rb#L55)), but instead of just returning a 401 devise retries authentication.
