### ISSUE TITLE
Configuration with google app email?

### ISSUE THREAD

**Issue by earnold** [apokalipto/devise_saml_authenticatable#97]
Thanks for this gem!

I'm trying to make it work with Google Apps. Roughly the instructions I'm following are [here](https://support.google.com/a/answer/6087519?hl=en). 

Google seems to provide either i) `SSO URL` and `Entity ID` and a certificate, or ii) `IDP metadata` which downloads as XML. 

I'm struggling to figure out which fields to put into the devise configuration. 

Here is what I have so far: 

```
config.saml_configure do |settings|
    settings.assertion_consumer_service_url     = "https://#{my_apps_domain}/users/saml/auth"
    settings.assertion_consumer_service_binding = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    settings.name_identifier_format             = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" # taken from google's metadata
    settings.issuer                             = "http://#{my_apps_domain}/saml/metadata"
    settings.authn_context                      = "" # is this okay blank?
    settings.idp_slo_target_url                 = "?????" # no idea where to get this value?
    settings.idp_sso_target_url                 = "https://accounts.google.com/o/saml2/idp?idpid=#{id-hidden}"
    settings.idp_cert                           = <<-CERT.chomp
-----BEGIN CERTIFICATE-----
# google cert
-----END CERTIFICATE-----
      CERT
  end
end
```

Does that look right? 

And in Google, I've configured configured `ACS URL` to be `https://#{my_apps_domain}/users/saml/auth` and `Entity ID` to be `
http://#{my_apps_domain}/users/saml/metadata`

I think this should be right, however, I am still getting this error: 

```
403. That’s an error.

Error: app_not_configured_for_user
```

Any thoughts on what could be causing the issue?

**Comment by adamstegman** [comment]
You don't need the SLO target URL, that's only if you want users to be logged out of your app when they log out of Google.

I'm not sure how to use `authn_context` but [ruby-saml documents it as most likely optional](https://github.com/onelogin/ruby-saml#metadata-based-configuration). I've definitely never used it 🙃 

Your issuer should be `/users/saml/metadata`, it's missing the `/users` prefix. It should also be HTTPS, just like the ACS URL. The issuer value may be causing the issue, but the error message reads to me like there's configuration that needs to be done in the IdP to allow your user to use it for SSO. When I googled that error message the first result also indicates that: https://github.com/omniauth/omniauth-saml/issues/116#issuecomment-249515259. So I'd suggest updating your issuer and making sure the IdP config is correct, and trying again.

**Comment by earnold** [comment]
@adamstegman Thanks for the catch on the issuer! I've fixed that. 

I'm starting to think the problem might be around the `Entity ID` that Google is asking for.

This is what the screen looks like: 

![screen shot 2017-07-03 at 12 35 26 pm](https://user-images.githubusercontent.com/169206/27805889-22ddb8b2-5fec-11e7-85bb-2204badd25a7.png)


Do you suspect that Entity ID would be a URL? A URI? I'm not finding much documentation on it.

**Comment by adamstegman** [comment]
I think your entity ID may be the same as your issuer URL.

**Comment by earnold** [comment]
Solved!

To future generations who find this. The `Entity ID` in google app configuration must _exactly_ match the `issuer`.  Google uses these two values to figure out which SAML apps have been approved. ([ref](https://support.google.com/a/answer/6301076?hl=en))

In my case I had an http vs https clash. 

Thanks for your help!
